### ISSUE TITLE
User login attribute validation may not have an email address matching constraint

### ISSUE THREAD

**Issue by cpkelley** [articulate/terraform-provider-okta#100]
By default, the `login` attribute for an OKTA User in the Base schema profile has a format constraint that it must match an email address. But this field constraint is configurable via the UI and can be configured to match any string. I have not found a way to configure it via the the API. See image below.  

Right now, the terraform provider limits login fields to match an email address:

```
"login": &schema.Schema{
	Type:         schema.TypeString,
	Required:     true,
	Description:  "User Okta login (must be an email address)",
	ForceNew:     true,
	ValidateFunc: matchEmailRegexp,
},
```

For my use case, I wanted to configure a "test" user with the login field set as not email compliant to validate that the User schema is properly configured via the UI, since I can't use terraform or the API to make this change in the user schema. 

Not sure if you were aware of this configurable `login` field constraint, or if this limitation is intentional, given that modifying existing attributes is not supported via the API. 

![user_form_sc](https://user-images.githubusercontent.com/1452169/51061503-883bc280-15c1-11e9-8da6-6be1295bc37f.png)

Here is the JSON object for the login schema after the UI change with the `pattern: ".+"` included: 
```
"base": {
            "id": "#base",
            "type": "object",
            "properties": {
                "login": {
                    "title": "Username",
                    "type": "string",
                    "required": true,
                    "mutability": "READ_WRITE",
                    "scope": "NONE",
                    "minLength": 5,
                    "maxLength": 100,
                    "pattern": ".+",
                    "permissions": [
                        {
                            "principal": "SELF",
                            "action": "READ_ONLY"
                        }
                    ],
                    "master": {
                        "type": "PROFILE_MASTER"
                    }
                },
```

**Comment by quantumew** [comment]
There are a few older resources here that need refactoring and user schema is one. Enforcing login to be an email indeed appears incorrect. Let me fix that.

**Comment by quantumew** [comment]
I think you are correct, let me look into that.
