### ISSUE TITLE
Errors building the provider.

### ISSUE THREAD

**Issue by kpdhindsa** [articulate/terraform-provider-okta#108]
Hi, i'm getting the following errors while cloning the provider and also while running "make-build plugins". Please advise. FYI, I'm using the required versions of Terraform and Go.

`ab1234:terraform-provider-okta user$ go get -u github.com/articulate/terraform-provider-okta
 github.com/hashicorp/terraform/helper/logging
../../hashicorp/terraform/helper/logging/transport.go:53: undefined: json.Valid
 github.com/hashicorp/terraform/vendor/golang.org/x/net/http2
../../hashicorp/terraform/vendor/golang.org/x/net/http2/server.go:220: s.RegisterOnShutdown undefined (type *http.Server has no field or method RegisterOnShutdown)
 github.com/hashicorp/terraform/configs/configload
../../hashicorp/terraform/configs/configload/testing.go:21: t.Helper undefined (type *"testing".T has no field or method Helper)
 github.com/hashicorp/terraform/config
../../hashicorp/terraform/config/testing.go:9: t.Helper undefined (type *testing.T has no field or method Helper)`

**Comment by quantumew** [comment]
Can you clarify what version of Go you are using? I think I ran into this in a different project. If I remember right it was a change between Golang 1.8 and 1.9.

**Comment by quantumew** [comment]
We may need to change our Go version recommendation but I would actually recommend just installing Go 1.11. I often use https://github.com/moovweb/gvm to make switching between versions simple. Although I have to admit gvm has its annoyances.

**Comment by quantumew** [comment]
Docs were never updated when we went to TF 0.11. Corrected this cd2992b72d2ed85d953366a8535752488ce417a6. Thanks for reporting! Get to Golang 1.9 or greater and you shouldn't have any issues.

**Comment by quantumew** [comment]
I updated another aspect of the docs that were out of date. You can now run `make` which installs deps properly then builds. The issue here was likely wrong dependency version (running `make` now installs deps and builds plugins) or due to Go < 1.9 being installed.
