### ISSUE TITLE
Errors when "go getting" the code / building the plugin

### ISSUE THREAD

**Issue by paranoidd** [articulate/terraform-provider-okta#111]
Disclaimer: this is different issue than listed in https://github.com/articulate/terraform-provider-okta/issues/108

First, some information regarding the build environments I have attempted:
- go 1.11.5 @ macOS 10.14.2
- go 1.11.5 @ Debian Linux 9.7 (in docker)
- go 1.11.5 @ Alpine Linux 3.8 (in docker)
- go 1.9.7 @ Debian Linux 9.7 (in docker)

In each one of the environments, executing `go get -u github.com/articulate/terraform-provider-okta` would end up in the following error:

```
--> linux/amd64 error: exit status 2
Stderr: # github.com/articulate/terraform-provider-okta/okta
okta/app.go:139:3: cannot use &revealPass (type *bool) as type bool in field value
okta/app.go:158:3: cannot use &autoSubmit (type *bool) as type bool in field value
okta/app.go:160:4: cannot use &hideMobile (type *bool) as type bool in field value
okta/app.go:161:4: cannot use &hideWeb (type *bool) as type bool in field value
okta/app.go:166:58: undefined: "github.com/okta/okta-sdk-golang/okta".App
okta/app.go:169:55: too many arguments in call to client.Application.GetApplication
okta/app.go:201:70: not enough arguments in call to client.Application.CreateApplicationGroupAssignment
	have (string, string, "github.com/okta/okta-sdk-golang/okta".ApplicationGroupAssignment)
	want (string, string, "github.com/okta/okta-sdk-golang/okta".ApplicationGroupAssignment, *query.Params)
okta/app.go:220:82: not enough arguments in call to client.Application.DeleteApplicationGroupAssignment
	have (string, string)
	want (string, string, *query.Params)
okta/app.go:275:61: not enough arguments in call to client.Application.AssignUserToApplication
	have (string, "github.com/okta/okta-sdk-golang/okta".AppUser)
	want (string, "github.com/okta/okta-sdk-golang/okta".AppUser, *query.Params)
okta/app.go:304:72: not enough arguments in call to client.Application.DeleteApplicationUser
	have (string, string)
	want (string, string, *query.Params)
okta/app.go:304:72: too many errors
```

I have attempted running `go get -d` (which succeeded) and then `make build-plugins`  but that ultimately ended up in the same error state.

I will be thankful for any kind of assistance, and I will greatly appreciate hints that would allow me to successfully build this exciting plugin.

Thank you!

**Comment by quantumew** [comment]
I think this will be a repeat of #97. You will want to get dependencies with `make deps` which uses `dep` and ensures you get the right versions/branches of our dependencies. Eventually we will switch this to go modules which will work much better. I will make that more clear in the docs

**Comment by paranoidd** [comment]
@quantumew thank you for super fast answer. I have issued `make deps` prior to `make build-plugins` and it has indeed resolved my issue!

I still need(ed) to to use `-d` flag to go get the source (instead of `-u`), but that is a minor note.

Thank you again for your assistance!

**Comment by quantumew** [comment]
Good point `-d` makes sense. I will update the docs. Thanks for the feedback!
