### ISSUE TITLE
Can't use environment variable to specify org name or API token

### ISSUE THREAD

**Issue by mbudnek** [articulate/terraform-provider-okta#122]
The README says the organization name and API token can be specified with the environment variables `OKTA_ORG_NAME` and `OKTA_API_TOKEN`, but when I tried using those environment variables instead of giving the values in the provider declaration in my terraform file, the provider complained:

```
Error: provider.okta: "api_token": required field is not set
```

**Comment by quantumew** [comment]
Yup that should indeed work. Can I see your provider config? You have to make sure you do not specify any values so it takes the default. It does not override the provider config block. https://github.com/articulate/terraform-provider-okta/blob/master/okta/provider.go#L51-L68

**Comment by mbudnek** [comment]
Looks like this was my fault.  Turns out I wasn't running the script I thought I was, and the environment variables weren't getting set.  When I do things correctly the provider works correctly.
