### ISSUE TITLE
HTTP Proxy support

### ISSUE THREAD

**Issue by bodgit** [articulate/terraform-provider-okta#130]
Not sure if this is specifically for this provider or the underlying library used to make the API calls, but this provider doesn't seem to be respecting the standard HTTP proxy environment variables and is trying to go direct to the Okta API which won't work in my environment.

I have the following set: `http_proxy`, `HTTP_PROXY`, `HTTPS_PROXY` & `NO_PROXY`

These are working fine for the AWS Terraform provider to direct it through our corporate proxy and as I understand it, the standard Go HTTP client should respect them and JFW but that doesn't appear to be the case.

**Comment by quantumew** [comment]
This is likely the underlying SDK. Are there particular resources you notice this on or all? We use an amalgam of two SDKs at this time so the answer might save a little time. No worries if you are not sure, should be easy enough to test.

**Comment by bodgit** [comment]
I've created articulate/okta-sdk-golang#4 which seems to fix things mostly for me in that it just picks up the standard environment variables however that bypasses all of the documented proxy configuration methods. Looking through the code though, I'm not sure the proxy configuration is ever used, it doesn't configure the HTTP client in any way that I can see.
