### ISSUE TITLE
Binary isn't recognized as provider by terraform

### ISSUE THREAD

**Issue by hgibsonqb** [articulate/terraform-provider-okta#134]
The binary name for the latest release is named terraform-provider-okta_2.20.0_x4 but for terraform to recognize it, the name has to be terraform-provider-okta_v2.20.0_x4

**Comment by quantumew** [comment]
You are correct, fixing...

**Comment by quantumew** [comment]
https://github.com/articulate/terraform-provider-okta/commit/0bb884e34d015189691b32f6e89257bf8b7d9915
