### ISSUE TITLE
new resource | app_push_group ?

### ISSUE THREAD

**Issue by robwaldron-flg** [articulate/terraform-provider-okta#139]
Not sure if a new resource or to be embedded into an existing resource makes more sense, but using the Okta Org2Org as an example; Push Groups enables pushing users from a group in a master Okta org to be pushed into a specified group (or created on demand) in another Okta org.

In this documentation, it exists here: https://saml-doc.okta.com/Provisioning_Docs/Okta-Org2Org_Provisioning.html, but as Push Groups is a feature beyond Org2Org and can be other apps that support Push Groups (e.g. O365), it could be enabled as a standalone resource that can be used where required.

**Comment by ahsanali** [comment]
I dont think there is a okta public api endpoint to do this. I wrote a python script and used local executioner to achieve adding 76 groups. May be you can do the same.
