### ISSUE TITLE
resource_identity_provider | support SAML

### ISSUE THREAD

**Issue by robwaldron-flg** [articulate/terraform-provider-okta#140]
From what I can tell, the current resource is configured for OIDC. Maybe these should be split into resource_identity_provider_oidc, resource_identity_provider_saml or add in the configuration options for saml?

https://developer.okta.com/docs/api/resources/idps/#add-saml-2-0-identity-provider

**Comment by quantumew** [comment]
Yea this resource predates me. I might do what I did with other resources and deprecate it, then create a resource for each type. it makes for a much more cogent schema.
