### ISSUE TITLE
Support for setting "Application notes for admins" in apps

### ISSUE THREAD

**Issue by bodgit** [articulate/terraform-provider-okta#143]
Our Okta account now has apps that are both manually set up and managed by Terraform, it will be a long time I suspect before everything in there is 100% managed by Terraform.

I figured it might be a good idea to utilize the "Application notes for admins" field in an app to add a "Managed by Terraform" hint so people know that if they manually edit the settings that they will be reverted by a future Terraform run:

![image](https://user-images.githubusercontent.com/559268/56648898-06593c00-667c-11e9-8ada-1e33778a9000.png)

This field doesn't seem to be currently managed by Terraform, would it be hard to add support to be able to manage it? (and probably the "Application notes for end users" field above it)

**Comment by quantumew** [comment]
Unfortunately this field is not exposed by the API. I can put in a request for it but likely it would take a bit.

**Comment by bodgit** [comment]
Bah, I figured as much given everything else can be managed. It makes sense to be able to manage it, so if you can request API support that would be great. For now I'll just manually update the note to warn any other admins.
