### ISSUE TITLE
Access external key assigned by okta

### ISSUE THREAD

**Issue by hgibsonqb** [articulate/terraform-provider-okta#145]
Okta assigns an ID to saml applications (separate from the app id attribute) which is needed to access the app without an authorization token. For example, the url to access app meta without an authorization token is  https://{okta domain}/{app extrenal key}/sso/saml/metadata. 

I'm currently finding the okta external key by extracting it from my saml applications http_post_binding (which has the format https://{okta domain}/app/{app name attribute}/{app external key}/sso/saml). Is there a better way to access the external key using the latest provider version (2.24) and if not can the external key be added as an attribute?

**Comment by quantumew** [comment]
Good question, currently that is only exposed in the metadata so no. I can add this property this evening though. I will extract it from the metadata and drop it on `external_key`. Look for it in 2.25.0
