### ISSUE TITLE
Administrator Roles: add support for role targets

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#15]
https://developer.okta.com/docs/api/resources/roles

App Roles

**Comment by rtlong** [comment]
@quantumew Was this effort abandoned? I just encountered this missing functionality and would very much like to have it. I'm willing to implement, but I would like to understand why this issue was closed before I do.

**Comment by quantumew** [comment]
@rtlong the group portion of this was implemented (link below) but the app roles were not. I am guessing it was an oversight. Reopening and updating.


https://github.com/articulate/terraform-provider-okta/tree/master/examples/okta_group_roles

**Comment by rtlong** [comment]
See this issue in the migrated repo: terraform-providers/terraform-provider-okta#13

**Comment by noinarisak** [comment]
Hi @rtlong! Thanks for your interest in the provider. We officially apart of the Hashicorp Terraform ecosytem which means this repo will be read-only in the near future. Sady, we are still in the middle of moving all GH Issues over to [terraform-providers/terraform-provider-okta](https://github.com/terraform-providers/terraform-provider-okta).

This issue will be closed and moved.
