### ISSUE TITLE
okta_app structure 

### ISSUE THREAD

**Issue by shawnferry** [articulate/terraform-provider-okta#155]
Conditionally failing okta_app_saml on missing resources only at apply time seems suboptimal.

I *think* [integrated](https://www.okta.com/okta-integration-network/) apps should have a different resource. Possibly `okta_app_preconfigured`, `okta_app_integrated`, `okta_app_from_catalog` (selecting catalog because okta says "search catalog" for integrations). 

I'm not sure there is a clean answer but I also don't like okta_app_from_catalog_saml, okta_app_from_catalog_oath at all.  It *seems* from a very small test set the auth specific values are not available to change from the UI so it may be fine to just ignore them.

For example (currently works as okta_app_saml)
```
resource okta_app_from_catalog "greenhouse" {
  preconfigured_app = "greenhouse"
  label             = "greenhouse - TF"

  app_settings_json = <<JSON
  {"subdomain":"terraform-test"}
JSON
}
```

**Comment by quantumew** [comment]
Yea I agree 100%. I was pretty new when I made this decision and I didn't think it through. I definitely plan on deprecating "preconfigured_app" setting and separating it. I have thought the real solution is a resource per distinct app, for instance, `okta_app_aws_console`. The resources will be super thin and rely on shared functions/schemas/resources. I would have to do a bit more research to see if this actually makes sense or if you plan is more suitable or if i should do both for more flexibility.

I will also say Okta's APIs around their catalog apps is subpar. There are many things that just cannot be configured. For instance group profiles, api integrations, etc. 

Anyways I will get to this one soon, I have been annoyed by this as well.
