### ISSUE TITLE
app_settings_json isn't 

### ISSUE THREAD

**Issue by shawnferry** [articulate/terraform-provider-okta#156]
[struct ApplicationSettings](https://github.com/okta/okta-sdk-golang/blob/2395a5f0ddc8840b41566277432f0589f2570108/okta/applicationSettings.go) has members App and Notification.

I'm too new at this to understand how the code is working [parsing the payload](https://github.com/articulate/terraform-provider-okta/blob/a277407821f4af8f69fbf91ae7befb1b14a37ae6/okta/resource_app_saml.go#L520) seems to make sense but I don't understand enough of the basic language primitives or terraform's implementation to understand why notifications appears to be silently dropped and other keys (signOn) appear to be consumed.

I agree that the range is wide and also it looks to have custom implementation possibilities.  It seems like this could be 
```
"settings_json": { <N consumed keys>, "app": ..., "notifications": ..., ...}
```
or
```
app_settings_json:
notification_settings_json:
```
but it isn't clear that this list wouldn't grow. 

From the REST API ({{url}}/api/v1/apps) maybe the Go SDK is returning things notably differently, which would obviate a lot of this.
```
"settings": {
            "app": {
                "subdomain": "terraform-test"
            },
            "notifications": {
                "vpn": {
                    "network": {
                        "connection": "ZONE",
                        "exclude": [
                            "ALL_ZONES"
                        ]
                    },
                    "message": "What does this look like in the config?",
                    "helpUrl": null
                }
            },
            "signOn": {
                "defaultRelayState": null,
                "ssoAcsUrlOverride": null,
                "audienceOverride": null,
                "recipientOverride": null,
                "destinationOverride": null
            }
        },
```

**Comment by quantumew** [comment]
At a cursory look it appears the config is not represented in the resource. I will be get this added. Thanks for the report!
