### ISSUE TITLE
Tests: Test results should be compared to the Okta resource

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#16]
Add support in our tests to verify the values in the Okta resource correspond with the test results

**Comment by PurrBiscuit** [comment]
So long as the resource `Read` functions are doing what they should be doing then configuration drift should be picked up during tests automatically.  Test flow is `terraform plan` -> `terraform apply` -> `terraform plan (with a refresh)`.  The resource's `Read` function is used during the plan/refresh which reaches out to the resource and, if using the d.Set("") ResourceData function, should be able to detect config drift between the actual resource and it's terraform configs.
