### ISSUE TITLE
Policy and rule model seems wrong

### ISSUE THREAD

**Issue by shawnferry** [articulate/terraform-provider-okta#165]
Looking at the existing policy and policy rules constructs I *think* there are type specific details vs the higher level abstractions and this also needs a refactor. 

I think [policy.go](https://github.com/articulate/terraform-provider-okta/blob/master/okta/policy.go#L42) has members groups_[included|excluded] incorrectly it should instead have members conditions and settings as a [policy object](https://developer.okta.com/docs/api/resources/policy/#policy-object).

Then policy_rules.go would have the definition for the [rules object](https://developer.okta.com/docs/api/resources/policy/#rules-object)

Both policy and policy rule would consume conditions objects...

**Comment by quantumew** [comment]
Took a look at this and there is definitely room for improvement here. Was able to get #124 in without touching too much of it but it definitely could use work.
