### ISSUE TITLE
Terraform 0.12 Support

### ISSUE THREAD

**Issue by robwaldron-flg** [articulate/terraform-provider-okta#167]
Not sure if this would be on the roadmap, but 0.12 RC1 was released today with a planned GA release in the coming weeks.

https://www.hashicorp.com/blog/releasing-terraform-0-12-0-rc1

**Comment by quantumew** [comment]
Yup it is on the radar. Last I looked there was no migration guide so I am not really sure what needs to change yet. I plan on digging into that soon though.

**Comment by Ginja** [comment]
👋 

Thanks for the provider first off :) Here is the migration guide we're following for our internal providers:

https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html
