### ISSUE TITLE
Client Credentials Should Be A Valid Grant Type for a Web App

### ISSUE THREAD

**Issue by ryber** [articulate/terraform-provider-okta#169]
Hello,
 
First of all, this project is awesome, thank you so much for creating this.

Second, I believe the validation logic for oauth apps is off.

I have a resource like so:
```ruby
resource "okta_app_oauth" "terraform-test" {
  label          = "Terraform Test App"
  type           = "web"
  grant_types    = ["authorization_code", "client_credentials"]
  redirect_uris  = ["http://d.com/"]
  response_types = ["code"]
}
```

this results in this error:
```
failed conditional validation for field "grant_types" of type "web", it can contain authorization_code, implicit, refresh_token and must contain authorization_code, received authorization_code, client_credentials
```

Web applications can be valid client credential applications:
![clientcredentials](https://user-images.githubusercontent.com/145359/57722146-763f5e80-764b-11e9-8eb7-695d80a9ef8a.png)

I believe (I'm new to go). clientCredentials needs to be added here:
https://github.com/articulate/terraform-provider-okta/blob/a277407821f4af8f69fbf91ae7befb1b14a37ae6/okta/resource_app_oauth.go#L38

Thank you. I'd issue a PR but at the moment I'm having some issues resolving some of your make dependencies which I am trying to get around,.

**Comment by quantumew** [comment]
@ryber Good catch, I can get a fix out for this in a minute. I am tempted to remove that validation logic and let the API handle it. For now I will fix this particular case.
