### ISSUE TITLE
Ability to retrieve issuer from auth server

### ISSUE THREAD

**Issue by amtineo** [articulate/terraform-provider-okta#172]
I'm in need of retrieving the issuer set by Okta but I get an error saying that the resource does not have attribute 'issuer'.

Any ideas how I can retrieve it? Is it supported?

**Comment by quantumew** [comment]
Looks like a bug. I for some reason made issuer optional. Should be computed. Fix coming shortly..

**Comment by amtineo** [comment]
Thanks for your promptly response. Hopefully you can get it in soon =)

**Comment by quantumew** [comment]
Just released the fix in v2.39.0.

**Comment by amtineo** [comment]
Worked like a charm! Thanks again!
