### ISSUE TITLE
[feature request] shared credentials file

### ISSUE THREAD

**Issue by shantanugadgil** [articulate/terraform-provider-okta#178]
Terraform version: 0.12.0
Provider version: 3.0.0

Would it be possible to add functionality like the "shared credentials file", like that of the AWS provider?

Use case:
When using multiple Okta accounts, in the `provider "okta"` block, I can just mention the "provider profile" name and then, safely store the actual profile details in my dotfile like, say `~/.terraform_okt_provider.conf`.
I know, I can put my settings in the environment, but that limits the settings to a single Okta account, and I have to be always careful of the env variables.

**Comment by quantumew** [comment]
Love this idea, will tackle this soon.

**Comment by shantanugadgil** [comment]
Any luck with? I would have definitely submitted a PR had I been more of a gopher! 🐿️😇

**Comment by quantumew** [comment]
@shantanugadgil totally forgot about this one. I will plan on doing it after I wrap up mappings resource. My time has been limited lately unfortunately. Feel free to take a crack at it, glad to give guidance!
