### ISSUE TITLE
'Use PKCE' when creating a okta_app_oauth native resource 

### ISSUE THREAD

**Issue by maneeshsahu** [articulate/terraform-provider-okta#188]
**Is your feature request related to a problem? Please describe.**
I am trying to create a native oauth app using TF. I need it to use pkce instead of client authentication

**Describe the solution you'd like**
I need to create an app that uses pkce instead of client authentication

**Describe alternatives you've considered**
Looked at the source code, but havent been able to figure it out

**Additional context**
This is my tf file that I used to create the resource
```resource "okta_app_oauth" "android-browser-sign-in-2" {
  label          = "Android Browser Sign-In 2"
  type           = "native"
  grant_types    = ["authorization_code", "refresh_token"]
  redirect_uris  = ["abc.browser-sign-in:/callback"]
  login_uri = "abc.browser-sign-in:/callback"
  response_types = ["code"]
  omit_secret = true
  post_logout_redirect_uris  = ["abc.browser-sign-in:/logoutCallback"]
}
```

**Comment by quantumew** [comment]
For PKCE your config is perfect but one minor tweak, set `token_endpoint_auth_method` to `none`. The provider is setting the default to basic auth. No clue why the value is none but that is a question for Okta :-D. Also, Terraform doesn't do conditional defaults well, if it did I would default this to `none` on native apps.

https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_app_oauth.go#L120-L129

**Comment by maneeshsahu** [comment]
Thanks Andy! I am closing the issue.

**Comment by rachrdfds** [comment]
This should be in the official documentation (https://www.terraform.io/docs/providers/okta/r/app_oauth.html) so you don't have to find the answer in a GitHub issue, IMHO.
