### ISSUE TITLE
Support for G Suite email aliases

### ISSUE THREAD

**Issue by c-knowles** [articulate/terraform-provider-okta#192]
**Is your feature request related to a problem? Please describe.**

I think in the okta_user resource code, currently it seems not possible to use custom_profile_attributes of type string array. At least I was trying to get to a working example and didn't find anything so far. This is needed to support email aliases in G Suite, see 
https://help.okta.com/en/prod/Content/Topics/Provisioning/Google/email-alias.htm.

This passes validation but cannot be applied:
```
custom_profile_attributes = {
  emailAliases = ""
}
```

This way produces the following error when applied:
```
custom_profile_attributes = {
  emailAliases = []
}
```

```
custom_profile_attributes (emailAliases): '' expected type 'string', got unconvertible type '[]interface {}'
```

Setting to this ensures no changes in a terraform plan:
```
custom_profile_attributes = {
  emailAliases = "<[]interface {} Value>"
}
```

**Describe the solution you'd like**

Support for string array custom attribute for email aliases.

**Describe alternatives you've considered**

This seems to be supported in github.com/hashicorp/terraform/helper/schema so assuming this could be tweaked in the plugin, haven't found any alternatives yet.

**Comment by quantumew** [comment]
I ran into this a month or two ago, I thought I was able to correct it but I bet I didn't fully test it. Let me drop an acceptance test, get it to fail, then correct it. Thanks for reporting!

**Comment by quantumew** [comment]
Ok this makes no sense. Fix on its way!
https://github.com/articulate/terraform-provider-okta/blob/d2e5dc26407d38a1b813dcd22f92908b28f796b5/okta/user.go#L409-L413
