### ISSUE TITLE
Cannot add users to groups (says user is not found/404)

### ISSUE THREAD

**Issue by c-knowles** [articulate/terraform-provider-okta#194]
## Expected Behavior

Adding users by ID to a group like in the example https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_group/okta_group_with_users.tf should be valid and not produce a 404 for valid lists of users.

## Actual Behavior

Applying terraform with a user added to a group says the user is not found (404) even when the user does exist.

## Steps to Reproduce the Problem

I'm using plugin v2.40.0, I had a look through the code for both this and the latest version but didn't see any change that would affect the problem.

Say we have this group and added a user called `user_name` to the users list a bit like the example from above:

```
resource "okta_group" "GroupName" {
  name        = "GroupName"
  description = "some description"
  users       = ["${okta_user.user_name.id}"]
}
```

The plan looks ok to start with:

```
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ okta_group. GroupName
      users.#:          "0" => "1"
      users.1234567890: "" => "email@domain.com"

Plan: 0 to add, 1 to change, 0 to destroy.
```

But then applying:

```
okta_group.GroupName: Modifying... (ID: 04fklfhsbvaop29xFsl19D)
  users.#:          "0" => "1"
  users.3914676666: "" => "email@domain.com"
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error occurred:
	* okta_group.GroupName: 1 error occurred:
	* okta_group.GroupName: The API returned an error: Not found: Resource not found: email@domain.com (User), Status: 404 Not Found
```

I investigated and did a few curls to the `Add User to Group` API from https://developer.okta.com/docs/reference/api/groups/#add-user-to-group. It seems the `userId` in the APUI can only be the UID that Okta generates rather than the email/login as per the plan output. Then I checked the state file and the `.id` field for all users inside there is the login rather than the UID (which looks a bit like `04fklfhsbvaop29xFsl19D`). Actually the Okta UID doesn't appear to be stored anywhere in the state.

**Comment by quantumew** [comment]
This is bizarre, I am not sure how this would happen and last running this acceptance test it passed without any errors. Can you post the jist of your user tf config? I want to run exactly what you are running on 2.40.0. Also, you are right 2.40.0 should be fine.

**Comment by c-knowles** [comment]
The users are run in fine, nothing particular special just name, login, email etc. Some custom attributes but don’t think that will affect it. In your state files is the `id` field for a user the Okta generate one of the email address?

**Comment by quantumew** [comment]
Got it. Negative, the user ids are uuids. I will post a quick confirmation that the acceptance are indeed passing still.

**Comment by c-knowles** [comment]
We imported all our users from Okta to the Terraform... and imported by email. Maybe that’s the cause?

**Comment by quantumew** [comment]
That's it! I am presuming they were imported via email but the resource uses the passthrough importer, which sets the id to whatever you provide it and does a read on the user. This actually works fine until you reference id because Okta GET user endpoint takes an email but all other non user endpoints require an id.

**Comment by quantumew** [comment]
This makes me think, I could add a property to the user resource that is `user_id` so you could choose to import via email and still have access to the user id.

**Comment by c-knowles** [comment]
I think `id` should be uniform across all resource, it makes sense to use the Okta UID. So I guess that means get the user fully on import. When logging any plan with a user/group change it’s always best to log email I think as the UID is not human readable. Not sure how feasible that it.

**Comment by quantumew** [comment]
Yea this would be really nice but unfortunately this would result in more API calls to get the email associated with the user. There is no way to reference anything in a resource other than what is provided.

**Comment by quantumew** [comment]
@tecnobrat brought up a really good point. We can update our user import to no longer use passthrough and actually support importing by login or by id. It will generate another request when an email is provided but I think that is totally acceptable. I will add that soon.

**Comment by c-knowles** [comment]
I think for import that is acceptable as it’s more a one off operation. Then we get down to the bit I mentioned above, but to clarify what I meant:

- `id` stored to terraform state should be uniform across all Okta resources, the Okta UID
- imports should be validated?
- when we import with email I assume the first API response does contain the ID, however if an additional call is needed that’s acceptable

My last point was more about subsequent plans/changes. I just wanted to ensure terraform plan logs are human readable which mean avoiding the UID. If there is a way to ensure terraform prints the `.login` that’s be helpful (currently if we change all our IDs I’m then assuming it’ll print all Okta UIDs in the plan).

**Comment by quantumew** [comment]
This comment linked below was referencing the last point, there is no mechanism for this in Terraform. Other than extraneous API calls or forcing consumers to pass the login of the user to the resource referencing it.
https://github.com/articulate/terraform-provider-okta/issues/194#issuecomment-505060927
