### ISSUE TITLE
Is it possible to set Single Logout URL?

### ISSUE THREAD

**Issue by mcdir** [articulate/terraform-provider-okta#200]
**Is your feature request related to a problem? Please describe.**
Setup Single Logout URL via terraform-provider-okta

**Describe the solution you'd like**
Just any kind possibility to setup  "Single Logout URL" the same as manual way in the "Edit SAML Integration>Show Advanced Settings"
Enable Single Logout > On,
Single Logout URL
SP Issuer

**Describe alternatives you've considered**
Didn't find

**Additional context**
![Selection_098](https://user-images.githubusercontent.com/745825/60425531-64b21600-9bfb-11e9-99c4-3d47a917930f.png)

**Comment by quantumew** [comment]
Did you try the `sso_url` setting? https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_idp_saml/basic.tf#L3

**Comment by mcdir** [comment]
Yes I've set this var, but unfortunately `sso_url` is `Single Sign On URL`. I need set `Single Logout URL`

**Comment by quantumew** [comment]
Oh silly me, I misread your comment. I actually am not aware of this setting so my brain ignored the `Logout` part. I am seeing a different UI then you are, need to figure out why this isn't exposed for me, then get it added to the schema!

**Comment by quantumew** [comment]
Silly me, I thought you were referring to a SAML IdP. Cool, let me get that added to the SAML app schema.

**Comment by quantumew** [comment]
Ok dug into this a bit more. Turns out Okta does not expose these settings via the API. I can toggle these settings and the API response does not change and they are undocumented. I will report this to Okta.

**Comment by mcdir** [comment]
@quantumew Thank you a lot for your support. I've asked the same things to OKTA, but they didn't answer (

**Comment by asemikov** [comment]
@quantumew 
Any updates on this? Any possible ways via Terraform or Okta API?
