### ISSUE TITLE
Provide an Option to PGP Encrypt client_secret

### ISSUE THREAD

**Issue by ryber** [articulate/terraform-provider-okta#202]
**Is your feature request related to a problem? Please describe.**
Hi, I've noticed that when creating applications that application secrets are stored in state. It would be nice to have an option where that is not kept but left in Okta.

**Describe the solution you'd like**
Maybe some kind of configuration to not keep secrets in state?

**Describe alternatives you've considered**
There are various options for encrypting state files including using Terraform Enterprise, but It would be even better if it didn't have the secrets at all to begin with

Thank you for providing this plugin! It's going to make my life sooooooo much better! 💯

**Comment by quantumew** [comment]
Have you tried the `omit_secret` setting? This is a unique setting so I should really have a clear example of it.

https://github.com/articulate/terraform-provider-okta/blob/a277407821f4af8f69fbf91ae7befb1b14a37ae6/examples/okta_app_oauth/oauth_app_remove_groups_and_users.tf#L20

**Comment by ryber** [comment]
Oh, yea, that's probably exactly what I want. Let me ask a follow up question. I plan on wiring this all up to our internal GitHub Enterprise and then letting teams do pull requests to create apps and get added to auth server policies. Using this setting (or even in the default behavior), do you have a recommendation on how I would communicate the clientId and secret that gets created?

**Comment by quantumew** [comment]
Okta's API is limited here. You can only get the `client_secret` on create so you would not be able to use a data source to get it. This really limits your options. Either store it in state or manually intervene.

With that said, I have seen some providers have an option to encrypt secrets so they are not stored in cleartext  in TF state (link below). If I provided a method such as this would it open your options up more? 

https://www.terraform.io/docs/providers/aws/r/iam_access_key.html#pgp_key

**Comment by ryber** [comment]
Yes, thank you very much. This can be closed, or you can keep it open and convert it to a reminder to update your doc maybe? Thanks again!
