### ISSUE TITLE
unified build for Terraform 0.11 and Terraform 0.12

### ISSUE THREAD

**Issue by shantanugadgil** [articulate/terraform-provider-okta#209]
**Is your feature request related to a problem? Please describe.**
I wish there were a single unified build for Terraform 0.11 and Terraform 0.12, just like the "terraform-provider-aws".
Using the older TF can then benefit from all the goodness of the provider updates.

**Describe the solution you'd like**
The new name which ends with "_x5" make the plugin incompatible with Terraform 0.11
The reason I want to hold onto TF 0.11.14 is that the "terraform fmt" is borked in the TF 0.12.

**Describe alternatives you've considered**
I keep two separate installation in "/opt/terraform-0.12" and "/opt/terraform-0.11" with each sub directory housing the plugins.

**Additional context**
none-yet.

**Comment by quantumew** [comment]
I am still on TF 0.11 and the latest plugin works fine for me. I might be missing something though, what error do you get running the latest provider?

**Comment by shantanugadgil** [comment]
OK, I just retried this and everything is working fine. I am pretty sure, I had split the two installations due to the 0.12 plugin (v3.x) not working with TF 0.11.x

Anyway, things are working, this is a non-issue:
```
$ /opt/terraform-0.11.14/bin/terraform --version
Terraform v0.11.14
+ provider.aws v2.18.0
+ provider.okta v3.0.5

```

**Comment by shantanugadgil** [comment]
after thinking about this some more ... When Terraform 0.12 downloads the AWS provider, the filename ends with `x4`, indicating it is backward compatible (as mentioned in the provider docs).

So, would it also make sense to make the okta provider file name end with `x4` rather than `x5` ???

_This is not a major concern, just a though._

**Comment by quantumew** [comment]
@shantanugadgil That is a good question. Going to reopen and investigate. Ostensibly the way it is now works as expected but I would still like to know for sure.

**Comment by quantumew** [comment]
@shantanugadgil Looks like you were right. Totally works with x5 but should be x4. All future binaries will follow this patter. Good call!
