### ISSUE TITLE
Support for setting a scope as default in authorization server

### ISSUE THREAD

**Issue by jeremie0** [articulate/terraform-provider-okta#212]
**Is your feature request related to a problem? Please describe.**
It is possible to create a scope in an authorization server and set it as a default scope.  But, the terraform provider doesn't support this yet.

**Describe the solution you'd like**
In ```okta_auth_server_scope``` resource it would be great if we could have an optional boolean setting for "default" or "isdefault".  
The setting is documented in the Okta API docs https://developer.okta.com/docs/reference/api/authorization-servers/#scope-properties
and the POST request to the scopes endpoint looks like this: ```{"consent":"IMPLICIT","metadataPublish":"NO_CLIENTS","name":"testdefault","description":"testdefault","default":true}```

**Describe alternatives you've considered**
I am able to manually set it after I've create the scope via TF.

**Comment by quantumew** [comment]
Good call, this should be a very simple addition.

**Comment by jralmaraz** [comment]
Anyway I can contribute by starting with a simple task like this ? Question coming from an infra guy who wants to start learning how to properly code :)

**Comment by quantumew** [comment]
@jralmaraz Yea go for it! Take a look here https://github.com/articulate/terraform-provider-okta/blob/master/DEVELOPMENT.md for some dev details. Let me know if you have any questions. This one might be as simple as adding the schema property, using it, and adding a test for it. I am not 100% on the restrictions of editing default policies though.

**Comment by jeremie0** [comment]
This was implemented in terraform-provider-okta 3.0.25
