### ISSUE TITLE
issuerMode required for social idp resource

### ISSUE THREAD

**Issue by chlsmith** [articulate/terraform-provider-okta#214]
Getting the following on my terraform apply step:

okta_idp_social.microsoft: 1 error occurred:
okta_idp_social.microsoft: The API returned an error: Api validation failed: issuerMode. Causes: errorSummary: issuerMode: 'issuerMode' is required., Status: 400 Bad Request.

Looking through the example and the code, I don't see issuerMode as something I can set.

**Comment by quantumew** [comment]
Interesting. I bet our Okta tenants are setup differently. I can successfully create one without issuer mode in my tenant but I likely don't have a custom domain setup. Let me get that setting added.

**Comment by chlsmith** [comment]
dang, you're quick!   Thanks for the quick check.

________________________________
