### ISSUE TITLE
terraform validate should fail if redirect_uris contains a fragment

### ISSUE THREAD

**Issue by jeremie0** [articulate/terraform-provider-okta#218]
**Is your feature request related to a problem? Please describe.**
If we configure a okta_app_oauth resource as: 

```
resource "okta_app_oauth" "sample123" {
  label       = "sample123"
  type        = "browser"
  grant_types = ["implicit"]
  redirect_uris              = ["http://localhost", "http://localhost:3000", "http://dev-api.company.com/testapi/v1passive/#/request", ]
  response_types             = ["token", "id_token"]
  omit_secret                = true
  token_endpoint_auth_method = "none"
  groups                     = ["${data.okta_group.everyone.id}"]
}
```
A terraform validate passes:
```
$ terraform validate
Success! The configuration is valid.
```

but when we terraform apply we get an error back from Okta:
```
Error: The API returned an error: Api validation failed: redirect_uris. Causes: errorSummary: redirect_uris: ''redirect_uris'' must not contain a fragment identifier.

```

**Describe the solution you'd like**
It would be great if ```terraform validate``` could catch this - not allow a redirect_uris that contains a # fragment character.

**Comment by quantumew** [comment]
Agree fully that it would be nice! Unfortunately Terraform ties our hands a bit here, since validation functions are supported on aggregate types in Terraform (Sets, Lists, and Maps). I will have a look though.
