### ISSUE TITLE
Support for "logo" when building applications

### ISSUE THREAD

**Issue by paullschock** [articulate/terraform-provider-okta#219]
When building applications via terraform, it'd be nice to be able to personalize the application by uploading a custom logo. 

From reviewing the API documentation for Okta (https://developer.okta.com/docs/reference/api/apps/#add-application) this does not yet appear to be supported, but I wanted to open an issue to track in case this changes. 

Possible implementation (pending implementation of the endpoint by Okta and valid input values) might be to use [existing file resources to pass in a base64](https://www.terraform.io/docs/configuration/functions/filebase64.html) version of the file.

**Comment by quantumew** [comment]
I was asked by Okta to supply the deficiencies in Okta's API that is limiting the provider so I will definitely pass this on.

**Comment by fatbasstard** [comment]
Hi @quantumew,

Do you happen to have an update on this?

**Comment by danielinclouds** [comment]
Hi, @quantumew @paullschock do you have any update on this?

**Comment by quantumew** [comment]
@fatbasstard @danielinclouds It is still only on their internal API only. Sorry for the delayed answer. We are close to transferring this over to Okta so hopefully that will create more visibility of limitations such as this. A public
