### ISSUE TITLE
can't opt-in to group user management when importing a group

### ISSUE THREAD

**Issue by joshk0** [articulate/terraform-provider-okta#220]
## Expected Behavior
When I import a group, and it contains some users, and my tf wants to manage the users, a plan should show that the group already has users and compare it against the tf list of users.

## Actual Behavior
Until the first apply, or until you adulterate the state to add a non-empty users array, terraform will not show an accurate delta of group users compared to what is in okta.

## Steps to Reproduce the Problem
1. create a group with 5 random users, manually
1. create a corresponding tf resource to manage the users of that group. Let's say keep 2 users, burn 3 from the original list, add 3 more
1. import that group from step 1 as the new tf resource
1. terraform plan should show that precise delta mentioned in step2 , however, it will instead say the group is empty and the 5 users from the tf are being added, ignoring whatever the group currently contains

**Comment by joshk0** [comment]
The proximate cause is probably [this line of code](https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_group.go#L119-L122)

If it could be modified to check and see if we are about to start managing the list of users on the next plan and then sync the group users, that would be great.

**Comment by quantumew** [comment]
Ah right, that makes sense. Let me write a test to replicate and get it fixed.
