### ISSUE TITLE
Regex filter type

### ISSUE THREAD

**Issue by c-knowles** [articulate/terraform-provider-okta#221]
Are there any examples for regex filters in SAML apps? e.g. the other values available for https://github.com/articulate/terraform-provider-okta/blob/2c238d5f7bf02487161a64e4c74e61a6b93e4756/examples/okta_app_saml/custom_saml_app_all_fields.tf#L25. I can't seem to get this attribute to work even based on this values from the example. Also could not find it in the Okta SDK at https://github.com/okta/okta-sdk-golang/blob/master/okta/samlAttributeStatement.go.

I was trying to set it like this:
```
  attribute_statements {
    type         = "GROUP"
    name         = "groups"
    filter_type  = "EXPRESSION"
    filter_value = ".*"
  }
```

Also tried `REGEX` and a few other values for filter type, all accepted but then once applied the app config in Okta is a filter of "None".

**Comment by quantumew** [comment]
@c-knowles yea I had to add this functionality to our fork of the SDK, just opened a ticket for that now that you reminded me https://github.com/okta/okta-sdk-golang/issues/76. I have some examples in my closed source TF. Let me get better examples committed here.

**Comment by quantumew** [comment]
Below should work, but it sounds like you tried this. I am using this personally so I would be surprised if there was a bug here but perhaps. Going to write a test for this specifically and link it here.

```
  attribute_statements {
    type         = "GROUP"
    name         = "groups"
    filter_type  = "REGEX"
    filter_value = ".*"
  }
```

**Comment by quantumew** [comment]
This is working for me but I found a bugfix for this in 3.0.4. I neglected to jot it down in the CHANGELOG. I fixed that in #222. I am thinking this will start working like a charm after an update.

**Comment by c-knowles** [comment]
Awesome! Upgraded to latest 3.0.10 and it's working now. Thanks a lot for the examples. I will leave the issue open in case you want to track the fork revert back to official SDK.

**Comment by c-knowles** [comment]
BTW, the latest version says it is upgraded to Terraform 0.12 but is it required? 3.0.10 appears to run ok with 0.11.14.

**Comment by quantumew** [comment]
Not required. Still works with 0.11. I will update the docs to make that clear.

**Comment by shantanugadgil** [comment]
@c-knowles a related discussion
https://github.com/articulate/terraform-provider-okta/issues/209
