### ISSUE TITLE
SAML app Requestable SSO URLs

### ISSUE THREAD

**Issue by c-knowles** [articulate/terraform-provider-okta#227]
Is it currently possible to set `Requestable SSO URLs` for SAML app configs? This option is available once `Allow this app to request other SSO URLs` is checked on on the SAML app setup page. I could not see an Okta API option so not sure it's even possible.

**Comment by quantumew** [comment]
Unfortunately Okta, for whatever reason, does not expose this via their API. Opening a feature request with them.
