### ISSUE TITLE
To be able to create users from a file in bulk

### ISSUE THREAD

**Issue by msmrnv1** [articulate/terraform-provider-okta#231]
I would like to be able to have an option to create users in bulk (e.g. define a list of users in JSON object) and assign them to a specific user group. I did not find any good way to do that using the current resources. 
Do you have any recommendation based on the current functionality or that will be a new feature?

**Comment by quantumew** [comment]
This would be a new feature. It would be a limited resource. Importing existing resource would be kind of a mess, it would be `{user_id}/{user_id}...`,  that would be a bit of a pain but scriptable. You also wouldn't get all of the schema goodness Terraform provides or any of the lifecycle ignore stuff. Maybe a beneficial nonetheless. Let me know if I am off track.

Pseudo example

```
resource okta_user_json_set my_set {
    json_payload = "${file("${path.module}/hello.txt")}"
}
```

It would require it be an array or a single object representing a user. It would then

**Comment by msmrnv1** [comment]
That will probably work. My use case is more focused on creating small number of the users with admin roles that can be different depending on environment. 
So I would be able to define a variable in dev.mycompany.tfvar file for my dev env (qa env will have qa.mycompany.tfvar) that will have something like this
super_admin_users: "{
  "users": [
    {
      "first_name": "\"Joe\"",
      "last_name": "\"Test\"",
      "login": "\"joe.test@company.com\"",
      "email": "\"joe.test@company.com\""
    },
    {
      "first_name": "\"Joe1\"",
      "last_name": "\"Test1\"",
      "login": "\"joe.test1@company.com\"",
      "email": "\"joe.test1@company.com\""
    }
  ]
}"

Then a new resource will be created..

resource okta_users company_admin_user{
  users = ["${var.super_admin_users}"]
  group_memberships = ["${okta_group.super_admin_group.id}"]

}

**Comment by quantumew** [comment]
Oh I see what you are saying. Cool, that is better than the JSON payload idea, because we get all of the Terraform goodness. I think this might already be possible, I will follow up shortly with an example or I will fail trying and mark this as a new feature.

**Comment by msmrnv1** [comment]
great, thanks!

**Comment by jralmaraz** [comment]
That example would be great! Did we have any ? Thanks.
