### ISSUE TITLE
Associate app parameters with a group

### ISSUE THREAD

**Issue by c-knowles** [articulate/terraform-provider-okta#234]
Is it possible to change attributes at the group level of an app assignment? For example if adding groups to the G Suite app assignments, we can add an organization unit value there in the UI but wondering if it's possible to do in terraform?

**Comment by quantumew** [comment]
I haven’t looked into this particular scenario but likely there is no API support. We had a very similar need with the AWS SAML App roles and found the API was readonly. I will investigate this one shortly. If it is not supported I can open a feature request for it.

**Comment by c-knowles** [comment]
I had a look at the API and tried a few calls. This is available via `profile` on Application Group Properties - https://developer.okta.com/docs/reference/api/apps/#application-group-properties and is custom to each app. e.g. Lucidchart has `canEdit` whereas G Suite has `orgUnitPath`.

**Comment by quantumew** [comment]
Good deal thanks for investigating. We saw the same thing with AWS SAML app but the profile property was read only, that was the one thing I needed to verify. I set aside some time this weekend should have time to look at this.

**Comment by c-knowles** [comment]
Ah ok, I hadn't tried those calls before but tried just now. Seems to align to the docs where `priority` and `profile` are readonly=false. I tried a few calls of this form below and was able to change information in the profile:
```
curl -v -X PUT \                                                                                                    
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: $OKTA_API_AUTH" \
-d '{"priority":19,"profile":{"orgUnitPath":"testing"}}' \
"https://${OKTA_DOMAIN}.okta.com/api/v1/apps/${APP_ID}/groups/${GROUP_ID}"
```

**Comment by quantumew** [comment]
Awesome! That sounds really promising.

**Comment by encron** [comment]
Is there any update on this yet? In our use case we'd like to assign AWS IAM roles to our Okta groups through the `okta_app_group_assignment`. Through the API it's possible to do this like @c-knowles said with a `PUT` call: 
```
PUT {{url}}/api/v1/apps/{{appId}}/groups/{{groupId}} 
with a JSON body:
   { "profile": {         "samlRoles": [             "[aws-account-number-or-alias] -- role-name"         ]     } } 
```

So it would be nice if it was possible to pass the `profile` value when creating the `okta_app_group_assignment`.

**Comment by quantumew** [comment]
Sorry for the delay y'all. I have had no time to get to this. Unfortunately all of my energy on this project has now been directed towards #269. Fortunately this is potentially really simple so I am going to get to it this weekend and post an update for you Monday. Thanks!

**Comment by encron** [comment]
Cool! Thanks for taking the time ;)
