### ISSUE TITLE
Internal Okta API Resources

### ISSUE THREAD

**Issue by quantumew** [articulate/terraform-provider-okta#235]
Can we start to build resources for things that have no public API? In my opinion, we can as long as it we very clearly mark these resources as "contractless" and output a warning message.  We should make it clear that Okta reserves the right to change the API without a version increment being that it is leveraging a `/internal` endpoint.

The other caveat is auth. Some of these endpoints do not take API tokens. We will potentially have to work around this.

**Comment by nijave** [comment]
What's the auth flow look like on these? I was playing around and it looks like you need a cookie and CSRF token for the internal APIs. I just grabbed them out of the browser but I imagine automating will require a bit more work

**Comment by quantumew** [comment]
@nijave unfortunately, I have not explored this at all since opening it. I am still sticking to my old approach, block tickets without APIs and open a feature request with Okta via https://ideas.okta.com. With that said, I sort of assumed this would not be pretty if it was plausible at all. If you get a chance to dig deeper, any info would be much appreciated. Thanks!

**Comment by nijave** [comment]
> @nijave unfortunately, I have not explored this at all since opening it. I am still sticking to my old approach, block tickets without APIs and open a feature request with Okta via https://ideas.okta.com. With that said, I sort of assumed this would not be pretty if it was plausible at all. If you get a chance to dig deeper, any info would be much appreciated. Thanks!

I _think_ aws-okta is doing something that might be useful here to create an Okta session by scraping through the normal GUI. See https://github.com/segmentio/aws-okta/blob/master/lib/okta.go

**Comment by nijave** [comment]
After spending some time setting up directory sync it looks like the internal APIs (or at least some of them are Java Spring SOAP services). I suspect SWSS authorization is referring to Spring Web Security Service
