### ISSUE TITLE
Creation of policy rule signon fails

### ISSUE THREAD

**Issue by msmrnv1** [articulate/terraform-provider-okta#236]
I am trying to create the okta_policy_rule_signon resource that has network connection ZONE and network exclude defined e.g.

resource okta_policy_rule_signon admin_rule_signon {
  policyid       = "${okta_policy_signon.admin_signon.id}"
  name           = "Internal Network"
  access         = "DENY"
  status         = "ACTIVE"
  network_connection = "ZONE"
  network_excludes = ["00pmuh1fjohUG5oD80h7"]
}

I am getting the following error. But I did specified the exclude in the resource

Error: HTTP Method: POST - URL: https://d1.oktapreview.com/api/v1/policies/00pmuh1fjohUG5oD80h7/rules: - HTTP Status Code: 400, OKTA Error Code: E0000001, OKTA Error Summary: Api validation failed: conditions.network, OKTA Error Causes: [{conditions.network: You should either include or exclude network zones when you use zones in the policy rule.}]

**Comment by quantumew** [comment]
I 👃a bug in the provider. I wonder if it is sending both unintentionally. Let me cook up a test real quick.

**Comment by quantumew** [comment]
Ok yea looks like I was trying to do right thing but the logic wasn't quite right. #237 works for me.

**Comment by quantumew** [comment]
Ok just posted v3.0.14 with #237. I was able to create this resources properly after this change. Should be 💯 now.
