### ISSUE TITLE
Issue with the user creation with group and role assignments

### ISSUE THREAD

**Issue by msmrnv1** [articulate/terraform-provider-okta#238]
I am creating a user that gets assigned to a group and the role gets assigned to the group. It works great when I run it once. However if I run it second time, it gives me the following error

Error: [ERROR] Error Updating Admin Roles On User: The API returned an error: Not found: Resource not found: gramupp46qf7QZyxU0h7 (RoleAssignment)

 180: resource okta_user admin_user1{

I have something like this:

resource okta_group super_admin_group {
  name        = "Super Admin"
  description = "Super Admin Group"
}

resource okta_group_roles  super_admin_group_role {
  group_id    = "${okta_group.super_admin_group.id}"
  admin_roles = ["SUPER_ADMIN"]
}

resource okta_user admin_user1{
  first_name = "Joe"
  last_name  = "Smith"
  login      = "joe.smith@company.com"
  email      = "joe.smith@company.com"
  group_memberships = ["${okta_group.super_admin_group.id}"]
  depends_on = [okta_group.super_admin_group, okta_group_roles.super_admin_group_role]
}

**Comment by quantumew** [comment]
Interesting, I use this same pattern in several places and have not run into this. The error appears to be coming from an attempt to update the user admin roles. Did this user previously have admin roles directly assigned? I’d be curious to see the plan if you have it handy. I think I have an idea of how it got in this state so I will try reproducing.

**Comment by msmrnv1** [comment]
No, it is a brand new user and it does not have any roles directly assigned to him. In fact, it happens with more every user I create using this approach. First time it works perfectly, but it fails when I run the second time with the exact same message for every user.

**Comment by quantumew** [comment]
Gotcha, should be easy to repro then. I will get it reproduced via an acceptance test and get a fix pushed out. I have a feeling the user admin roles are not playing nicely with the group admin roles resource.

**Comment by quantumew** [comment]
I forgot to mention you can likely get around this now by lifecycle ignoring the user attribute admin_roles

**Comment by msmrnv1** [comment]
Thanks, can you show the example of the work around?

**Comment by quantumew** [comment]
Sure thing. About to merge #239 with the fix but here is what you can do in the meantime

```
resource okta_user admin_user1{
    first_name = "Joe"
    last_name = "Smith"
    login = "joe.smith@company.com"
    email = "joe.smith@company.com"
    group_memberships = ["${okta_group.super_admin_group.id}"]

    lifecycle {
        ignore_changes = ["admin_roles"]
    }
}
```
