### ISSUE TITLE
New Resource: Okta Group App Assignment

### ISSUE THREAD

**Issue by christek91** [articulate/terraform-provider-okta#242]
**Is your feature request related to a problem? Please describe.**
For my use case, I have one set of Terraform Configurations that create and manage Okta Applications. I also have a separate set of Terraform Configurations that create and manage Okta Groups. 

The Groups and the Apps live in separate TF State, and have different lifecycles.

I'd like to be able to assign Applications to Groups in one of these TF States without having to manage both the App and the Group in that same TF state file.

**Describe the solution you'd like**
Ideally I could use a new resource `okta_group_app_assignment` to assign a Group to an Application. In my use case, the Groups and Apps have well defined names, so the pattern I'd hope to use is to do something like:
```terraform
# my_app.tf
resource "okta_app_saml" "my-app" {
   # create my app
}
```

```terraform
# my_group.tf
resource "okta_group" "my-group" {
  # create group
}

data "okta_app_saml" "my-app" {
  # lookup app created in my_app.tf
}

# Assign Group to App
resource "okta_group_app_assignment" "my-app" {
  group = "${okta_group.my-group.id}"
  application = "${data.okta_app_saml.my-app.id}"
}
```

The implementation would probably just be a thin wrapper around the https://developer.okta.com/docs/reference/api/apps/#application-group-operations endpoints.

**Describe alternatives you've considered**
We've considered putting both the apps and the groups in the same TF State, but unfortunately that's not tenable with our architecture/use case. 

We've also considered using `exec` resources to call the Okta APIs for us as a poor man's version of this resource, but would much rather have a real resource. 

**Additional context**
It looks like someone may have requested a similar/duplicate feature earlier: https://github.com/articulate/terraform-provider-okta/issues/102

This is also similar to a pattern already in use w/ this provider with the `okta_app_oauth_redirect_uri ` resource: https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_app_oauth_redirect_uri/basic.tf#L17

**Comment by quantumew** [comment]
For sure, this is definitely on the radar. We have a case where for various reasons we don’t manage the app in TF at all but still want to manage group/user memberships. This is where the proposed resource(s) would come in handy. Going to tag this as an enhancement and see if I can get it in soon, it would be a fairly easy win.
