### ISSUE TITLE
resource_user_schema array_type typo

### ISSUE THREAD

**Issue by c-knowles** [articulate/terraform-provider-okta#243]
Not using it but noticed in passing - https://github.com/articulate/terraform-provider-okta/blob/75d707c136e86076cceec64ab45503416e2607bc/okta/resource_user_schema.go#L46 says `interger` not `integer`.

**Comment by c-knowles** [comment]
Same with https://github.com/articulate/terraform-provider-okta/blob/75d707c136e86076cceec64ab45503416e2607bc/okta/resource_user_base_schema.go#L45

**Comment by shantanugadgil** [comment]
👍  The typo is there in the description field as well. this can be easily fixed with a quick and simple PR. 🥇
