### ISSUE TITLE
Custom field for an app specific profile and setting this field for a user

### ISSUE THREAD

**Issue by c-knowles** [articulate/terraform-provider-okta#244]
**Is your feature request related to a problem? Please describe.**

In Okta it is possible to add a custom field under the Profile Editor of a specific application. This can then be customised for any user assignments to that app. It also appears to be possible in the Okta API. I have seen there is `okta_user_schema` and `okta_user_base_schema` but I did not spot a way in the terraform so think this is a feature request

**Describe the solution you'd like**

```
resource "okta_app_saml" "custom_saml_app" {
  ...

  users {
    id       = "${okta_user.username.id}"
    username = "${okta_user.username.email}"
    custom = {
      # some way to add value for a user for a given custom field
      tester_index_name = "custom_value_2"
	}
  }
}

resource "okta_user_schema" "custom_field" {
  index       = "tester_index_name"
  title       = "Tester"
  type        = "string"

  # some way to add custom field to a particular app Profile Editor
  master      = "${okta_app_saml.custom_saml_app.id}"

  required    = true
  permissions = "READ_ONLY"
  array_type = "string"
  enum        = [
    "custom_value_1",
    "custom_value_2",
  ]
  ...
}
```

**Comment by c-knowles** [comment]
Slightly related to https://github.com/articulate/terraform-provider-okta/issues/234 in that the field to user association is the same as the group association piece there.

**Comment by quantumew** [comment]
This is actually in the pipeline now, no issue for the work though so this is great. We will be adding an app user schema resource soon.

**Comment by quantumew** [comment]
Ok just got #247 merged, look for v3.0.17 release. It adds `okta_app_user_schema` which takes an `app_id` which will allow you to create custom user schemas for an application. Next I will be working on the app user/group profile part of it.

**Comment by Kyslik** [comment]
@jeremie0 thank you for this feature. 

---

Today we hit a problem though. If we specify that custom field is `required = true` and we create user assignment within the okta_app without the custom attribute then `terraform apply` fails (note that plan went OK).

Shortened failing example:

```
resource okta_saml_oauth test {
  // SNIP
  users {
    id       = "${okta_user.name.id}"
    username = "${okta_user.name.email}"
  }
}

resource okta_app_user_schema test {
  app_id      = "${okta_app_oauth.test.id}"
  // SNIP
}
```

It's not just about the validation. Given that we specify the custom attribute there is a cyclic dependency...

**Comment by quantumew** [comment]
@Kyslik tbh It was an early mistake to add nested `users` set on application (see #248 ). At some point we will deprecate that. For now, you can use the new resource `okta_app_user` (see #249) and just add an ignore. That reminds me I will add an issue to update our examples to use this approach.
```
lifecycle {
  ignore_changes = ["users"]
}
```
