### ISSUE TITLE
User Profile Mappings

### ISSUE THREAD

**Issue by msmrnv1** [articulate/terraform-provider-okta#246]
Is there any way to update the User Profile Mapping for Social IdP? I need to be able to update the mapping between the google IdP and Okta schema as well as the rules on create and update. Looks like it's also one of the internal APIs that is used to update this from the console, but I hope there is a way to do it via terraform.

**Comment by quantumew** [comment]
There is no public API for profile mappings unfortunately. I will make sure there is a feature req opened with Okta and I will  investigate the internal API to see if it is viable.

**Comment by joshuatalb** [comment]
@quantumew @msmrnv1 - there's a mapping API in the docs, found here: https://developer.okta.com/docs/reference/api/mappings/#getting-started.

Would this be enough to achieve the result you're after, @msmrnv1?

We also would like to control our mappings via Terraform. If there's enough demand, I'll create a PR with new TF resources to manage them.

**Comment by quantumew** [comment]
I took a really quick glance at it but this looks promising. Adding the next up tag. We would also like to use this!

**Comment by jralmaraz** [comment]
+1 for the mappings :)

**Comment by msmrnv1** [comment]
Is this enhancement planned soon?

**Comment by quantumew** [comment]
I unfortunately have not had time to make contributions here so I am not sure. Also, I will be decreasing my contributions to this project and will let Okta take it over. Contributions are definitely welcome!

**Comment by quantumew** [comment]
This is something that has been asked for a lot. Going to make time this weekend to get it in. Should be an easy enough one anyways.

**Comment by zoltanpeto** [comment]
+1, much needed. Any progress on this one?

**Comment by quantumew** [comment]
Made some good progress then lost the time to wrap it up. Should be able to find a few hours this week to get a PR open. Apologies on the delay.
