### ISSUE TITLE
Nested Resources

### ISSUE THREAD

**Issue by quantumew** [articulate/terraform-provider-okta#248]
At the advent of this project we followed the pattern of nesting resources. For instance, `okta_user` takes resources for the user but also takes `group_memberships`, which is a separate API. In my opinion, this was a mistake, I suggest we deprecate these properties and instead make association resources. This allows for maximal flexibility and prevents issues such as #220 where a single thing can be managed in multiple ways. You do not have to create an `okta_user` to associate a user with a group (you can use a data source if you like). Admittedly this is verbose but I think it is the right path forward and matches the normal Terraform idiom.

I still need to dig into this to be sure there is no way to support all approaches without any downsides.

It would look like this
```
resource okta_user me {
    email = "andy@example.com"
}

resource okta_group me {
    name = "me"
}

# In some cases we could also do the plural version
resource okta_group_membership me {
    group_id = "${okta_group.me.id}"
    user_id  = "${okta_user.me.id}"
}
```

**Comment by williamtheaker** [comment]
This would be helpful when combined with `okta_group_roles` so we could use Terraform to define a list of superadmins with already existing users.

**Comment by quantumew** [comment]
@williamtheaker can you elaborate? I have an idea of how this would work currently but I want to be sure I am on the same page. I am thinking you could use a user(s) data source to list users, push users to `okta_group` via the users attribute, then assign that group the appropriate role(s).

**Comment by williamtheaker** [comment]
Ideally I could define Okta user data sources by Okta id, similar to how the [AWS provider handles IAM users](https://www.terraform.io/docs/providers/aws/d/iam_user.html).

I was thinking it would look like this:

```
data "okta_user" "example" {
  id = "00ub0oNGTSWTBKOLGLNR"
}

resource "okta_group" "okta_super_admins" {
  name        = "Okta Super admins"
  description = "Users with Super Admin privileges on Okta. Managed by Terraform."
}

resource "okta_group_roles" "super_admin" {
  group_id    = "${okta_group.okta_super_admins.id}"
  admin_roles = ["SUPER_ADMIN"]
}

resource okta_group_membership "okta_super_admins" {
    group_id = "${okta_group.okta_super_admins.id}"
    user_id  = "${okta_user.example.id}"
}
```

**Comment by quantumew** [comment]
I guess I assumed if you had the id you wouldn't need to look it up. You would just refer to a `local` or `var`. Regardless, the below should work. Thanks for the reminder on the `okta_group_membership` resource. Hadn't opened a ticket for that yet.

```
data "okta_user" "example" {
  search {
    name = "id"
    value = "00ub0oNGTSWTBKOLGLNR"
  }
}

```

Should be easy enough to make that possible though: #335 #336

**Comment by williamtheaker** [comment]
Ah right, using locals didn't cross my mind. For sake of concision, `okta_group_membership` resources should probably accept a list for assigned users:

```
locals {
    user_id_1 = "00ub0oNGTSWTBKOLGLNR" 
    user_id_2 = "00ub0oTNGTSWRNLGLOKB" 
}

resource okta_group_membership okta_super_admins {
    group_id = "${okta_group.okta_super_admins.id}"
    user_ids  = [
      "${local.user_id_1}",
      "${local.user_id_2}",
    ]
```

**Comment by quantumew** [comment]
Hey @williamtheaker, `okta_group_membership` will always be a one to one but there is potential for another attachment resource there, I suppose but for now just iterate over your list (syntax is off the top of the old noggin so please validate 😄):

```
locals {
    user_ids = ["00ub0oNGTSWTBKOLGLNR", "00ub0oTNGTSWRNLGLOKB"]
}

resource okta_group_membership okta_super_admins {
    count = length(local.user_ids)
    group_id = "${okta_group.okta_super_admins.id}"
    user_id = "${local.user_ids[count.index]}"
}
```
