### ISSUE TITLE
group_filter_type validation is incorrect

### ISSUE THREAD

**Issue by jeremie0** [articulate/terraform-provider-okta#259]
## Expected Behavior
you should be able to create an okta_auth_server_claim with group_filter_type = "STARTS_WITH". https://developer.okta.com/docs/reference/api/authorization-servers/#claim-properties

## Actual Behavior
I receive an error from terraform validate:
Error: expected group_filter_type to be one of [START_WITH EQUALS CONTAINS REGEX], got STARTS_WITH

## Steps to Reproduce the Problem
This seems to be incorrectly specified in https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_auth_server_claim.go#L61
## Additional info
Add any other context about the problem here (e.g. screenshots, links)

**Comment by quantumew** [comment]
On it! Definitely a incorrect spelling and likely a missing acceptance test. Adding both soon.

**Comment by jeremie0** [comment]
thank you!
