### ISSUE TITLE
Travis builds fail because git.apache.org is down

### ISSUE THREAD

**Issue by conor-mullen** [articulate/terraform-provider-okta#267]
## Expected Behavior
Travis should load all module requirements.
## Actual Behavior
Building the provider fails
```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/travis/gopath/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:

	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out

go: error loading module requirements

Makefile:29: recipe for target 'build' failed

make: *** [build] Error 1

The command "make build" exited with 2.

```

## Steps to Reproduce the Problem
Attempt to build with Travis

## Additional info
People have reported the issue on the terraform repository
https://github.com/hashicorp/terraform/issues/22664

A suggested fix is to set `GOPROXY=https://proxy.golang.org` or use Go 1.13

**Comment by quantumew** [comment]
Ok got this updated to 1.13 on master. Thanks for reporting this!
