### ISSUE TITLE
Terraform Provider Development Program - Review

### ISSUE THREAD

**Issue by cgriggs01** [articulate/terraform-provider-okta#269]
Hey Team!

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the develop branch at git commit `ccfd6ab`

- [x] If a resource cannot be found(404) in the READ function, we should do a d.SetId("") to remove it from the statefile. You also wouldn't need to return an error then. Terraform will just treat it as a resource that never existed and try and create it.

- [x] The provider looks to be utilizing three different Okta Go SDKs; "github.com/okta/okta-sdk-golang/okta"
"github.com/articulate/oktasdk-go/okta”
“github.com/articulate/terraform-provider-okta/sdk”
It’d be best if the provider only used one SDK moving forward. 

- [x] The resource file naming convention is as follows, `resource_providername_resourcename.go` which means the file `resource_user.go` should be named `resource_okta_user.go` and its corresponding acceptance test should be named `resource_okta_user_test.go` , this should be follows across all resource and data source files.

- [x] You are already using Go Modules to manage the providers dependancies which is great, but in addition to that, we ask that you checkin all the required dependancies into a `vendor/` directory. 

- [x] The makefile should be replaced with  the GNUmakefile which is standard across all Terraform providers, feel free to copy the [NULL provider makefile](https://github.com/terraform-providers/terraform-provider-tls/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=okta

- [x] You will need to build website documentation that will be hosted on [Terraform.io](Terraform.io/docs/providers/index.html) for reach resource and data source, these are all written in Markdown with a ruby layout file for the sidebar formatting.  Check out the Github provider](https://github.com/terraform-providers/terraform-provider-github) website docs as a good example. 

- The Terraform.io website uses our terraform-website/ repository that is used as the middleman to sync all the terraform and provider documentation from all of their own repositories. To deploy/test the website locally follow the steps outlined in the README. When the provider is being release, our own internal engineers will make the changes to the website to include this provider. 
	- Once you've synced the current submodules there are 3 more steps required for adding you provider
	- Add the PROVIDER provider as a submodule to the terraform-website/ directory with: `git submodule add -b master https://github.com/REPO/terraform-provider-PROVIDER ext/providers/PROVIDER`
	- Then you'll have to create two symbolic links to this module, first change to the working directory terraform-website/content/source/docs/providers/ the run: `ln -s ../../../../ext/providers/PROVIDER/website/docs PROVIDER`
	- And then change to the working directory to "terraform-website/content/source/layouts/" to run: `ln -s ../../../ext/providers/PROVIDER/website/PROVIDER.erb`
	- After those additions, you can then run the "make website" target to spin up the website using Docker desktop. 

- [x] The acceptance tests run from my local machine only failed two of the ~80 tests.  Any thoughts on what is causing these test to fail?
```
--- FAIL: TestAccOktaGroupRuleCrud (3.59s)
    testing.go:568: Step 0 error: errors during apply:

        Error: The API returned an error: Api validation failed: validateRule. Causes: errorSummary: Invalid property articulateId in expression String.startsWith(user.articulateId,"auth0|"), errorSummary: conditions: Invalid expression

          on /var/folders/bf/6n0whcjn2x17rp19q0yc2vfc0000gn/T/tf-test825250803/main.tf line 5:
          (source code not available)
=== RUN   TestAccOktaMfaPolicy
--- FAIL: TestAccOktaMfaPolicy (1.66s)
    testing.go:568: Step 0 error: errors during apply:

        Error: [ERROR] Error Creating Policy: HTTP Method: POST - URL: https://dev-225468.oktapreview.com/api/v1/policies: - HTTP Status Code: 400, OKTA Error Code: E0000001, OKTA Error Summary: Api validation failed: settings.factors, OKTA Error Causes: [{settings.factors: Factor specified in the policy settings is not configured.}]

          on /var/folders/bf/6n0whcjn2x17rp19q0yc2vfc0000gn/T/tf-test231064437/main.tf line 5:
          (source code not available)
```

Thanks for all your work on this. Looking forward to releasing this provider officially!

**Comment by quantumew** [comment]
@cgriggs01 Really appreciate you digging into this, I will get started on these soon. Two quick notes on this.

Apropos the acceptance tests, both of those tests are failing for you and not for us due to missing test config. We have MFA factors flipped on already and we have `articulateId` defined in our user schema. Easy fix, just need to add those dependencies to the test config.

In reference to the SDK. We are phasing out `"github.com/articulate/oktasdk-go/okta”`, I will finish that process. The official SDK only defines a small number of endpoints we use. For the remainder we define our own functions (`“github.com/articulate/terraform-provider-okta/sdk”`) that use their request executor. This is the approach Okta recommends here https://github.com/okta/okta-sdk-golang#call-other-api-endpoints. Hopefully that is an acceptable approach.

**Comment by cgriggs01** [comment]
Hey @quantumew, 

That sounds great, thanks for clarifying those two points.

 I don't see an issue with the SDK implementation, but may I ask why the official SDK doesn't support all API endpoints?

**Comment by quantumew** [comment]
Cool, I have wondered the same. I will open an issue with them to inquire about it. Thanks!

**Comment by quantumew** [comment]
Hey @cgriggs01, I got all of these changes in with one caveat. We still have a split in the SDK but there is a plan outlined in #291. Can we move forward with that piece not quite finished? Okta has been antsy to get this out and I have had difficulty finding time for this work.

**Comment by cgriggs01** [comment]
This is great! Just a few more items then we can move forward to release. 

- [ ] The CHANGELOG formatting will have to be updated to conform to the standard provider format since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. 

- [ ] For the release of this provider we will be creating a new repository at github.com/terraform-providers/terraform-provider-okta/ because of this you'll need to update the provider from using the source path `github.com/articulate/terraform-provider-okta` to the new source path `github.com/terraform-providers/terraform-provider-okta`. 

- [ ] All official Terraform provider use a [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/) within each repo, could you swap the current MIT license for this [LICENSE](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/LICENSE)?

- [ ] The website docs you build look great, but there are a few broken links that don't have a file to point to. See [r/default_policy](https://github.com/articulate/terraform-provider-okta/blob/master/website/okta.erb#L109), [r/idp_saml_metadata](https://github.com/articulate/terraform-provider-okta/blob/master/website/okta.erb#L127), [d/everyone_group](https://github.com/articulate/terraform-provider-okta/blob/master/website/okta.erb#L31), [d/default_policy](https://github.com/articulate/terraform-provider-okta/blob/master/website/okta.erb#L28), [r/app_saml_metadata](https://github.com/articulate/terraform-provider-okta/blob/master/website/okta.erb#L70).  Could you add the corresponding documentation files for these objects?

Thanks for your work on this. Once these items are address we can move forward to the migration and release of the provider.

**Comment by quantumew** [comment]
Good catch on those broken links, just a couple flubs on my part. I will get these wrapped up this evening. Thanks again!

**Comment by quantumew** [comment]
Pushed up all of the requested fixes and changes. Opened a PR with import path update #300.

**Comment by cgriggs01** [comment]
Hey @quantumew,

Thanks for doing that, but there are still a
