### ISSUE TITLE
okta_auth_server_policy - client_whitelist - Recommendation on how to refer a client app ID

### ISSUE THREAD

**Issue by jralmaraz** [articulate/terraform-provider-okta#284]
Hi,

Firstly, sorry for raising so many issues, but there are some specific attributes or structure that are a bit hard to link their best usage just yet :)

Looking at the okta_auth_server_policy resource:

https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_okta_auth_server_policy.go

I would like to refer to an external oauth application resource in the client_whitelist. Looking at the description and examples I only found [\"ALL_CLIENTS\"].

The example would be:

client_whitelist = ["test"]

External resource in other tf file I would have an app as:

```
resource "okta_app_oauth" "test" {
  status         = "ACTIVE"
  label          = "test"
  type           = "web"
  grant_types    = ["implicit", "authorization_code"]
  redirect_uris  = ["https://localhost:8443/redirect_uri/"]
  response_types = ["code", "token", "id_token"]
}
```

In a set of resources related to an Authorization Server only (external to the app) I would have:

```
resource "okta_auth_server_policy" "test" {
  auth_server_id   = "${okta_auth_server.test.id}"
  status           = "ACTIVE"
  name             = "test"
  description      = "test"
  priority         = 2
  client_whitelist = ["test"]
}

```
This currently fails with:

`Error: The API returned an error: Api validation failed: conditions.clients.include. Causes: errorSummary: conditions.clients.include: Resource(s) not found: test (PublicClientApp)`

Thanks again for the amazing work!!!

**Comment by quantumew** [comment]
Yea there is no good example of this. I included one in #285.
