### ISSUE TITLE
Cannot perform actions on okta_auth_server.custom_auth_server resource when credentials_rotation_mode  is set to MANUAL

### ISSUE THREAD

**Issue by NeenuAVarghese** [articulate/terraform-provider-okta#287]
## Expected Behavior
Should be able to `plan`, `import` etc when the Okta Auth server credential setting is set to Manual
## Actual Behavior
```
Error: Error refreshing state: 1 error(s) occurred:
* okta_auth_server.custom_auth_server: 1 error(s) occurred:
* okta_auth_server.custom_auth_server: okta_auth_server.custom_auth_server: unexpected EOF
```

## Steps to Reproduce the Problem
1. Create a Okta AuthServer and set the  credential rotation mode to Manual. 
2. Create a Okta Auth Server resource  in terraform
3. Try to import the AuthSever state to terraform - You will see the above error
3. Change the credential rotation policy to Automatic
4. Try to import and that will work
5. Now change the settings in terraform resource to update the credential rotation to Manual and apply the changes - You will see the above error

**Comment by quantumew** [comment]
Interesting, I will get a test written up for this to repro and get it fixed. Likely a bug.

**Comment by NeenuAVarghese** [comment]
Awesome !! Thank you 😊
