### ISSUE TITLE
Terraform Module should pull in nested resource

### ISSUE THREAD

**Issue by NeenuAVarghese** [articulate/terraform-provider-okta#288]
## Actual Behavior
Cannot update `sub` claim in a resource in the Okta Auth server

## Steps to reproduce
Links to the relevant code, snippets
```
resource "okta_auth_server" "custom_auth_server" {
  audiences   = "https://example.com"
  name        = "AuthServer"
}
resource "okta_auth_server_claim" "sub_claim" {
  name           = "sub"
  status         = "ACTIVE"
  claim_type     = "RESOURCE"
  value_type     = "EXPRESSION"
  value          = "some-regex"
  auth_server_id = "${okta_auth_server.custom_auth_server.id}"
}
```
Apply the above changes and terraform will error out saying that the claim names conflict

# Expected Behavior
Terraform should be able to pull in nested resource of the auth server it creates in Okta
Note: This also causes issues when doing a terraform destroy as `sub_claim` is technically a system resource. In such cases, terraform provider should just destroy the auth server

**Comment by quantumew** [comment]
I don't believe the editing of system level claims was ever added to the provider. We will need to get this added!
