### ISSUE TITLE
Sporadic Okta connection refused errors

### ISSUE THREAD

**Issue by nijave** [articulate/terraform-provider-okta#292]
## Expected Behavior
It works

## Actual Behavior
```
Get https://my-org.okta.com/api/v1/apps/abc123/groups?limit=200: dial tcp 54.189.255.228:443: connect: connection refused
```

## Steps to Reproduce the Problem
Environment: Wired fiber connection
Steps: Run Terraform plan a bunch of times

## Additional info
It seems like this is possibly a rate limit? Has anyone else seen similar errors? Usually trying again or switching API keys works fine

**Comment by quantumew** [comment]
A rate limit issue should not cause a connection refusals. I have not ran into this myself yet and our tests run a lot of plans against our test org. This sounds like an Okta networking issue based on the error. You may want to report this to Okta. It would also be interesting to see the output of `TF_LOG=debug` when the failure happens.

**Comment by nijave** [comment]
> A rate limit issue should not cause a connection refusals. I have not ran into this myself yet and our tests run a lot of plans against our test org. This sounds like an Okta networking issue based on the error. You may want to report this to Okta. It would also be interesting to see the output of `TF_LOG=debug` when the failure happens.

Probably an issue with the internet connection, then although it was only popping up for Okta and not AWS which has significantly more connections (although it did previously)

**Comment by nijave** [comment]
I'll close this for now and assume it's on my end unless I find more info.
