### ISSUE TITLE
supporting format character restriction in Profile Editor

### ISSUE THREAD

**Issue by msmrnv1** [articulate/terraform-provider-okta#294]
I cant find a way to specify the pattern for format character restriction when I update a field in Okta schema. I tried to use something like this

resource "okta_user_schema" "schema_login" {
  index       = "login"
  title       = "Username"
  type        = "string"
  required    = true
  min_length  = 1
  max_length  = 50
  pattern     = "[\\^a-zA-Z0-9\\\\\\\\\\+\\@\\.\\_-]+"
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"
  validationType = "HARD"
}

![image](https://user-images.githubusercontent.com/53347685/66077154-61496600-e52d-11e9-9739-b52cab12a7a6.png)

**Comment by quantumew** [comment]
Thanks for the report. I was unaware this was even possible. Will get that property added this evening. Looks very straight forward.

**Comment by msmrnv1** [comment]
great, thanks

**Comment by msmrnv1** [comment]
I got the latest version, but it is not updating for me. I see see some warming, but I dont think that's a real issue
2019/10/03 20:05:52 [WARN] Provider "okta" produced an unexpected new value for okta_user_base_schema.schema_login, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .pattern: was cty.StringVal("[a-z0-9\\#\\_\\+\\@\\.-]+"), but now cty.StringVal("[qqqq]+")


Also, min_length and max_length is not supported in okta_user_base_schema resource.

**Comment by quantumew** [comment]
@msmrnv1 sorry about that, my acceptance tests were passing but I am wondering if it was a false positive. I will report back shortly. Will get the min/max lengths added as well.

**Comment by quantumew** [comment]
Looks like this property might be read-only, the API is ignoring it and I see no documentation for it. Going to ask Okta about it. Also, due to the way I constructed my test I got a false positive. Going to remove that prop for now and get min/max length added.

**Comment by quantumew** [comment]
Ignore my previous comment, looks like pattern, max_length, and min_length are all being ignored by the API. Going to work with Okta on this. Reverting my previous PR for now.
