### ISSUE TITLE
Add a new claim to default auth server

### ISSUE THREAD

**Issue by msmrnv1** [articulate/terraform-provider-okta#297]
I would like to add a new claim to the default authorization server. It looks like I can do only if I know the id of the authorization server. It is fine if I create a new one, but is it possible to add a new claim to the existing authorization server via terraform?

**Comment by quantumew** [comment]
@msmrnv1 you can grab the auth server id using the `okta_auth_server` data source. It would look like this

```
data "okta_auth_server" "test" {
  name = "Default"
}

resource "okta_auth_server_claim" "test" {
  auth_server_id = "${data.okta_auth_server.test.id}"
  ...
}
```

**Comment by quantumew** [comment]
@msmrnv1 Going to close this. Please reopen if you have any issues with this. Thanks!
