### ISSUE TITLE
UserBaseProfile: validate fields in terraform schema

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#30]
per the validation field here: https://developer.okta.com/docs/api/resources/schemas#user-profile-base-subschema

currently, added to CustomizeDiff for the users resource tests to check login & primary email addresses are formatted as emails. there are a few more fields to validate per the chart linked above.

**Comment by quantumew** [comment]
This was completed with a series of okta_user PRs #73 being the main one. Closing.
