### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by jralmaraz** [articulate/terraform-provider-okta#302]
When applying a series of okta_app_user_schema resources I encountered the following issue:

> When applying changes to okta_app_user_schema.impersonate_primaryPensionID,
> provider "okta" produced an unexpected new value for was present, but now
> absent.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.
> 

Tried to check the actual behaviour and only extra thing (apart from the huge DEBUG logs below) was that on each and every apply it was able to create 2 resources, then would fail.

Thanks.

Jose

**Comment by quantumew** [comment]
It sounds like you may be running into #144. Okta’s API will overwrite concurrent changes to the schema API. To avoid this while creating multiple schema items you can add a depends_on clause to one of them and have it reference the other one. This will ensure they are not concurrently created.

**Comment by jralmaraz** [comment]
Sounds good @quantumew , thanks for the update. I mainly opened this issue as I got "scared" with the error message. Cheers!

**Comment by quantumew** [comment]
Of course, no worries @jralmaraz. Did the `depends_on` clause fix it? I took a cursory look at it so I just want to make sure I understood the issue correctly.

**Comment by jralmaraz** [comment]
It did resolve, sorry about the delay.
