### ISSUE TITLE
User profile mapping

### ISSUE THREAD

**Issue by jralmaraz** [articulate/terraform-provider-okta#303]
**Is your feature request related to a problem? Please describe.**
Not an specific problem, but, the main need is to be able to automate the definition and setup of profile mappings at a user schema level

**Describe the solution you'd like**
We should be able to declare an expression between an Okta and an app user's to perform specific updates. Example: 

{
"properties": {
        "managerId": {
            "expression": "user.getLinkedObject(\"Manager\").managerId",
            "pushStatus": "PUSH"
        }
    }
}

**Describe alternatives you've considered**
The current alternative is to perform "manual" actions against the mappings API through Postman-like tool.

**Additional context**
https://developer.okta.com/docs/reference/api/mappings/#getting-started

-- needed to include escape char (

> \

)  so that it didn't terminate the expression early in the payload.

Logic,
-Pre existing:
	- Application, Application profile attributes
		-Assumption is that once a new application is made the mapping id is generated (can be clarified)

- Return all mappings
	-- {{url}}/api/v1/mappings
- Find the mapping from the (Known) app id, 
	-- i.e. target = application id
		(for the mapping from okta to application
		(for the reverse mapping, the source will be the application id)

- To pull the schema all I  think you would need to do is call {{url}}/api/v1/mappings and get the schema links (need a better understanding on properly extending the SDK to perform the relationship)
	-I.e.
	"_links": {
            "self": {
                "href": "https://INSTANCE.oktapreview.com/api/v1/mappings/mapId1"
            }
        }

**Comment by jralmaraz** [comment]
DRAFT/Skeleton for adding mappings to SDK:

package sdk

```
import (
	"fmt"

	"github.com/okta/okta-sdk-golang/okta"
	"github.com/okta/okta-sdk-golang/okta/query"
)

type MappingProperties struct {
	Properties struct {
		Attribute struct {
			Expression string `json:"expression"`
			PushStatus string `json:"pushStatus"`
		} `json:"attribute"`
	} `json:"properties"`
}

type Mapping []struct {
	ID     string `json:"id"`
	Source struct {
		ID    string `json:"id"`
		Name  string `json:"name"`
		Type  string `json:"type"`
		Links struct {
			Self struct {
				Href string `json:"href"`
			} `json:"self"`
			Schema struct {
				Href string `json:"href"`
			} `json:"schema"`
		} `json:"_links"`
	} `json:"source"`
	Target struct {
		ID    string `json:"id"`
		Name  string `json:"name"`
		Type  string `json:"type"`
		Links struct {
			Self struct {
				Href string `json:"href"`
			} `json:"self"`
			Schema struct {
				Href string `json:"href"`
			} `json:"schema"`
		} `json:"_links"`
	} `json:"target"`
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
}

func (m *ApiSupplement) RemovePropertyMapping(mappingId, id string) (*okta.Response, error) {
	url := fmt.Sprintf("/api/v1/mappings/%s/", mappingId)
	req, err := m.RequestExecutor.NewRequest("POST", url, nil)
	if err != nil {
		return nil, err
	}

	return m.RequestExecutor.Do(req, nil)
}

func (m *ApiSupplement) ListProfileMappings(mappingId string) ([]*Mapping, *okta.Response, error) {
	url := fmt.Sprintf("/api/v1/mappings", nil)
	req, err := m.RequestExecutor.NewRequest("GET", url, nil)
	if err != nil {
		return nil, nil, err
	}

	var mapping []*Mapping
	resp, err := m.RequestExecutor.Do(req, &mapping)
	return mapping, resp, err
}

func (m *ApiSupplement) GetSingleProfileMapping(mappingId string) ([]*Mapping, *okta.Response, error) {
	url := fmt.Sprintf("/api/v1/mappings/%s", mappingId)
	req, err := m.RequestExecutor.NewRequest("GET", url, nil)
	if err != nil {
		return nil, nil, err
	}

	var mapping []*Mapping
	resp, err := m.RequestExecutor.Do(req, &mapping)
	return mapping, resp, err
}

func (m *ApiSupplement) AddPropertyMapping(mappingId string, body Mapping, qp *query.Params) (*Mapping, *okta.Response, error) {
	url := fmt.Sprintf("/api/v1/mappings/%s/", mappingId)
	if qp != nil {
		url = url + qp.String()
	}
	req, err := m.RequestExecutor.NewRequest("POST", url, body)
	if err != nil {
		return nil, nil, err
	}

	mapping := body
	resp, err := m.RequestExecutor.Do(req, &mapping)
	return &mapping, resp, err
}

func (m *ApiSupplement) UpdateMapping(mappingId string, body Mapping, qp *query.Params) (*Mapping, *okta.Response, error) {
	url := fmt.Sprintf("/api/v1/mappings/%s/", mappingId)
	if qp != nil {
		url = url + qp.String()
	}
	req, err := m.RequestExecutor.NewRequest("POST", url, body)
	if err != nil {
		return nil, nil, err
	}

	mapping := body
	resp, err := m.RequestExecutor.Do(req, &mapping)
	if err != nil {
		return nil, resp, err
	}
	return &mapping, resp, nil
}

```

**Comment by quantumew** [comment]
Thanks for this @jralmaraz I believe this functionality would be covered under #246, basically profile mappings. Is there more to it then that? Also awesome work with the SDK skeleton feel free to open a PR

**Comment by jralmaraz** [comment]
Hi there! There was a quick response, I was trying to wrap this up before going for the weekend here. 

I ended-up raising a new one thinking that #246 was mainly focused on social IDP, but you're right, it is basically profile mappings only :)

**Comment by jralmaraz** [comment]
Also, I haven't make progress on defining the actual resource (something like resource_okta_user_profile_mapping.go), but happy to put some time on it if I start having a better view on doing it properly 👍

**Comment by quantumew** [comment]
Cool much appreciated @jralmaraz. I don't want to steal your thunder if you already have the work started, I can step away and just be here to help you out. Let me know if you want to pair on anything outside of my working hours, generally 8-4 CST. I will rename that other issue, you are right, that title makes it confusing.

**Comment by jralmaraz** [comment]
Perfect @quantumew, I have raised PR #304 .

Amazing, 5 to 7PM CST is 9 to 11AM AEST/Melbourne. It would be amazing to pair-up and get a better understanding on how o properly perform pointers' reference/dereference , etc. Also, if you would like to cover anything around https://github.com/quantumew/terraforming-okta during that too, it would be great (will reach out via e-mail for more details, have a great night!)

**Comment by quantumew** [comment]
Sounds good! Going to close this for now, we can use the existing issue to track the mappings work.
