### ISSUE TITLE
Import error - Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by lamjo** [articulate/terraform-provider-okta#307]
Running into an error when importing an app.

```
$ terraform import module.main.module.my_okta_app.okta_app_oauth.this 0oamr4ly1b9iw3wUI0h7 
module.main.module.my_okta_app.okta_app_oauth.this: Importing from ID "0oamr4ly1b9iw3wUI0h7"...
module.main.module.my_okta_app.okta_app_oauth.this: Import prepared!
  Prepared okta_app_oauth for import
module.main.module.my_okta_app.okta_app_oauth.this: Refreshing state... [id= 0oamr4ly1b9iw3wUI0h7]

Error: rpc error: code = Unavailable desc = transport is closing


Releasing state lock. This may take a few moments...
```

**Comment by quantumew** [comment]
This looks like it is a Terraform Core issue, https://github.com/hashicorp/terraform/issues/22349. Looks like I need to update to the new SDK.

**Comment by quantumew** [comment]
![Screen Shot 2019-10-22 at 10 03 06 AM](https://user-images.githubusercontent.com/14934291/67300167-2cd52400-f4b3-11e9-86ab-6eec7c8d718f.png)

**Comment by quantumew** [comment]
Need to look into why I cannot repro this. Now that I see the full stack trace in #311, this had nothing to do with the sdk. Thanks again to @fllaca for following this up.

**Comment by fllaca** [comment]
thanks @quantumew ! the small fix of my PR (#311) was detected because it happened to me when updating a okta_app_group_assignment. It only happened in the UPDATE operation, so CREATE (first `terraform apply`)  and READ (`terraform plan`) were working ok. You can reproduce the issue by creating a resource of that type, do `terraform apply`, then update the resource (change the group_id for instance) and try to `terraform apply` again, second terraform apply would fail.

**Comment by lamjo** [comment]
Update: same error with v3.0.31

**Comment by quantumew** [comment]
Gotcha, let me get those reproducing tests written as intended and get a correction out. Will have time in the morning to get a fix out. Thanks for the report!

**Comment by quantumew** [comment]
@lamjo Can you send me your config and maybe the full stack trace? I still can't repro this after adding another step in the test to ensure it runs an update. I must be missing something else. I can repro it before the fix in 3.0.31 so I am wondering if something else is going on for you. Thanks!

**Comment by quantumew** [comment]
Dug into this and realized due to the way Okta's API exposes endpoints for app users/groups I had to add some special import logic for those resources. Running tests now, look for release v3.0.32 very soon.

**Comment by lamjo** [comment]
Update: same error with v3.0.32

```
$ terraform import module.main.module.my_okta_app.okta_app_oauth.this 0oamr4ly1b9iw3wUI0h7 
module.main.module.my_okta_app.okta_app_oauth.this: Importing from ID "0oamr4ly1b9iw3wUI0h7"...
module.main.module.my_okta_app.okta_app_oauth.this: Import prepared!
  Prepared okta_app_oauth for import
module.main.module.my_okta_app.okta_app_oauth.this: Refreshing state... [id=0oamr4ly1b9iw3wUI0h7]

Error: rpc error: code = Unavailable desc = transport is closing


Releasing state lock. This may take a few moments...
```

**Comment by quantumew** [comment]
@lamjo #311 was conflated with this issue because Terraform spit out the same error so I assumed you were importing a group assignment. There was a legitimate issue there which I resolved but it had nothing to do with what you were hitting. I see now with fresh eyes, you are importing a single oauth app. I cannot reproduce this with the OAuth app. Can you give me the debug logs with your API token headers redacted? `TF_LOG=debug terraform import <id>`. Apologies for not seeing this right away.

**Comment by lamjo** [comment]
@quantumew - thanks for continuing to help with this. Here are the debug logs..

https://gist.github.com/lamjo/46e90bfd8784fab0c972e37e5b59ed59

**Comment by quantumew** [comment]
NP, OK that was the ticket. It is panicking on this line https://github.com/articulate/terraform-provider-okta/blob/master/okta/app.go#L201. It should be checking if the response is nil before attempting to do anything with it. Once that is fixed you will get an actual error back that will tell you why it is failing to make the request. Should have time to fix it over lunch today.

**Comment by quantumew** [comment]
@lamjo Pushed up v3.0.36. Try again and report back. The error should no longer get swallowed.

**Comment by lamjo** [comment]
Now seeing the following error:
```
$ terraform import module.main.module.my_okta_app.okta_app_oauth.this 0oamr4ly1b9iw3wUI0h7 
module.main.module.my_okta_app.okta_app_oauth.this: Importing from ID "0oamr4ly1b9iw3wUI0h7"...
module.main.module.my_okta_app.okta_app_oauth.this: Import prepared!
  Prepared okta_app_oauth for import
module.main.module.my_okta_app.okta_app_oauth.this: Refreshing state... [id=0oamr4ly1b9iw3wUI0h7]

Error: Get https://./api/v1/apps/0oamr4ly1b9iw3wUI0h7: dial tcp: lookup .: no such host
```

But why is Host "."?
```
2019-11-19T15:02:06.274-0800 [DEBUG] plugin.terraform-provider-okta_v3.0.36_x4: -----------------------------------------------------
2019-11-19T15:02:06.274-0800 [DEBUG] plugin.terraform-provider-okta_v3.0.36_x4: 2019/11/19 15:02:06 [DEBUG] Okta API Request Details:
2019-11-19T15:02:06.274-0800 [DEBUG] plugin.terraform-provider-okta_v3.0.36_x4: ---[ REQUEST ]---------------------------------------
2019-11-19T15:02:06.274-0800 [DEBUG] plugin.terraform-provider-okta_v3.0.36_x4: GET /api/v1/apps/0oamr4ly1b9iw3wUI0h7 HTTP/1.1
2019-11-19T15:02:06.274-0800 [DEBUG] plugin.terraform-provider-okta_v3.0.36_x4: Host: .
2019-11-19T15:02:06.274-0800 [DEBUG] plugin.terraform-provider-okta_v3.0.36_x4: User-Agent: okta-sdk-golang/0.1.0 golang/go1.13 darwin/amd64 
2019-11-19T15:02:06.274-0800 [DEBUG] plugin.terraform-provider-okta_v3.0.36_x4: Accept: application/json
```

**Comment by quantumew** [comment]
@lamjo Perfect. What does your provider config look like?

**Comment by lamjo** [comment]
@quantumew - Here's my provider config:
```
provider "okta" {
  org_name  = element(split(".", var.okta_url), 0)
  api_token = "mytoken"
  base_url  = join(".", slice(split(".", var.okta_url), 1, length(split(".", var.okta_url))))
}
```
The okta_url is something like "my-org.oktapreview.com". I have no problem with creating Okta apps.

**Comment by quantumew** [comment]
@lamjo Gotcha, those values must not be getting set. IIRC the SDK simply joins them on `.`. Interestingly enough our provider is accepting empty strings. Will have to set a min length on those to avoid this situation.
