### ISSUE TITLE
Missing parameter 'Login initiated by'

### ISSUE THREAD

**Issue by wiciu125** [articulate/terraform-provider-okta#310]
When configuring OAUTH in terraform there is no option to define `Login initiated by` parameter.
After successfully creating application the default option for it is "App only".
As a result, when trying to open page by clicking on application in okta an error 404 appears.
To  change it to "Either Okta or App" manual action is required from the okta admin page.

The below configuration is for our Grafana 
```
resource "okta_app_oauth" "grafana" {
  label                      = "Grafana"
  type                       = "web"
  grant_types                = ["authorization_code", "implicit"]
  redirect_uris              = ["https://URLTOTHEGRAFANA/login/generic_oauth"]
  response_types             = ["code", "id_token"]
  token_endpoint_auth_method = "client_secret_basic"
  login_uri                  = "https://URLTOTHEGRAFANA"
  hide_web                   = true
}
```

**Comment by quantumew** [comment]
Thanks for reporting, likely a missing attribute, let me get that added.

**Comment by quantumew** [comment]
Arghhhh so frustrating. This is not exposed via the public app api. Rather it is exposed on `/api/v1/internal/apps/<appId>/settings/oidc`. Opening a feature request with Okta.

**Comment by wiciu125** [comment]
Thank you start working on that. Waiting for any update.

**Comment by fatbasstard** [comment]
Really missing this option, any update on this @quantumew ?

**Comment by quantumew** [comment]
@fatbasstard I have never had a feature request accepted let alone completed so likely no update 😆. I will check this evening. I have been planning on shooting my Okta contact some tickets, the pain points of their API. I will be sure to include this one.
