### ISSUE TITLE
Error verifying checksum for provider "okta" during Terraform init

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [articulate/terraform-provider-okta#317]
## Expected Behavior

Terraform Registry contains an actual checksum of sources
`terraform init` command doesn't fail

## Actual Behavior
```hcl
# Configure the Okta Provider
provider "okta" {
  org_name  = var.okta_organization_name
  base_url  = var.okta_base_url
  api_token = var.okta_api_token
}
```

```bash
$ terraform init

Initializing provider plugins...
- Checking for available provider plugins...

Error verifying checksum for provider "okta"
The checksum for provider distribution from the Terraform Registry
did not match the source. This may mean that the distributed files
were changed after this version was released to the Registry.


Error: unable to verify checksum
```

## Additional info
Terraform version:
`Terraform v0.12.12`

Could you please verify an actual provider state in the registry?

**Comment by quantumew** [comment]
Are you using the provider here? Or letting terraform pull one down? This repo is becoming an official provider but the process was halted by Okta. I believe the initial release is still sitting in the registry and I have no clue if it is setup properly or not. You can find a prebuilt binary in the releases tab of this repo.

**Comment by ivan-sukhomlyn** [comment]
@quantumew 
I defined the **okta** provider in the Terraform configuration. In this case, Terraform can't download and validate provider configuration properly.
Yes, I've fixed this with downloaded binary from the releases page and pre-installed it to the plugin  directory by path `~/.terradorm.d/plugins`
Thanks for your reply

**Comment by quantumew** [comment]
I will talk to Hashicorp and see if they can pull that binary down until Okta OKs it.

**Comment by alkar** [comment]
@quantumew thanks for the update on this!
Can we reopen this issue so that we can track updates on the matter?

**Comment by quantumew** [comment]
@alkar Good point, agree this should stay open.

**Comment by flyinbutrs** [comment]
Apologies, newbie here...  how can I work around this until Hashicorp updates their repo?

**Comment by quantumew** [comment]
@flyinbutrs No worries, you will want to grab the appropriate binary from the Github Releases, or build your own using the README instructions, then drop it in your `~/.terraform.d/plugins` directory.


https://www.terraform.io/docs/configuration/providers.html#third-party-plugins 
Optional, if you want to build it yourself: https://github.com/articulate/terraform-provider-okta#building-the-provider

**Comment by flyinbutrs** [comment]
Ha, I had figured it out and was just typing out an edit apologizing for the stupid question :).

Thanks!

**Comment by dijitali** [comment]
@quantumew - any idea if Okta are aware of this issue and intending to fix it?

I've just raised a support case with them to see if that can unblock this.

**Comment by alkar** [comment]
> @quantumew - any idea if Okta are aware of this issue and intending to fix it?
> 
> I've just raised a support case with them to see if that can unblock this.

Hi @dijitali, as far as I know Okta are aware of this issue and I believe are working towards a resolution.

**Comment by noinarisak** [comment]
Hi all,

Okta and Hashicorp are working on making the provider official. More to come!

**Comment by noinarisak** [comment]
Closed. We are official! 🎉

**Comment by ivan-sukhomlyn** [comment]
Awesome news 🥇 
Thanks for your job!
