### ISSUE TITLE
Allow for creation of other app types

### ISSUE THREAD

**Issue by mikn** [articulate/terraform-provider-okta#318]
**Is your feature request related to a problem? Please describe.**
Whilst trying to provision a "Microsoft RDP (MFA)" type application, I find that there is no resource that describes an application that would support those settings.

**Describe the solution you'd like**
I would like to be able to provision app types outside of Bookmark/OAuth/SAML/Three-field/Secure Password and SWA.

**Additional context**
Browsing the source code, I cannot find any resource that implements the CreateApplication() interface of the general application struct. I also do not find any app resource that provides the "MFA_AS_SERVICE" as a sign-on type in the Okta provider.

Should we implement a generic `okta_app_custom` which can take more settings, kind of matching the `CreateApplication` function (found here: https://github.com/okta/okta-sdk-golang/blob/master/okta/application.go#L121)?
Another alternative is to implement a specific resource for `rdp_mfa` and/or MFA_AS_SERVICE?

For reference, this is the API response for the Microsoft RDP (MFA) application type:
```json
  {
    "id": "{REDACTED}",
    "name": "mfa_rdp",
    "label": "Microsoft RDP (MFA)",
    "status": "ACTIVE",
    "lastUpdated": "2019-11-08T05:38:40.000Z",
    "created": "2019-11-08T05:38:39.000Z",
    "accessibility": {
      "selfService": false,
      "errorRedirectUrl": null,
      "loginRedirectUrl": null
    },
    "visibility": {
      "autoSubmitToolbar": false,
      "hide": {
        "iOS": true,
        "web": true
      },
      "appLinks": {
        "mfaAppHelpLink": true
      }
    },
    "features": [],
    "signOnMode": "MFA_AS_SERVICE",
    "credentials": {
      "userNameTemplate": {
        "template": "${source.login}",
        "type": "BUILT_IN"
      },
      "signing": {}
    },
    "settings": {
      "app": {
        "mfaAppInstanceId": "{REDACTED}"
      },
      "notifications": {
        "vpn": {
          "network": {
            "connection": "DISABLED"
          },
          "message": null,
          "helpUrl": null
        }
      }
    },
    {REMOVED FOR BREVITY}
  }

**Comment by quantumew** [comment]
Totally agree. The app resources were essentially built around Okta's API docs, which leave out use cases such as these. A custom app resource would cover a lot of use cases, especially given that `app_settings` just expects JSON. We could potentially get rid of the `preconfigured_app=<catalog_app_name>` since most of the unique settings are under `app_settings`, at least iirc.

**Comment by mikn** [comment]
Okay, I'll see if I can put up a PR by tomorrow :+1: 
Any thoughts on naming? I'll go for `okta_app_custom` until I hear other votes.

**Comment by quantumew** [comment]
@mikn 🙇  +1 on the name from me. Although part of me wants to name it `okta_app`. It is a generic application resource. Although I think that might confuse people into using that when the more specific implementation is more suitable.

**Comment by jralmaraz** [comment]
Great stuff @mikn , will keep an eye on this one (very useful use-case :) )

**Comment by mikn** [comment]
Right, I hit a snag with the implementation. It seems that the Okta API doesn't actually support creating a `Microsoft RDP (MFA)` application as of now as it seems that the UI flow creates another resource that isn't exposed through the API and links them up (I have an open ticket with Okta support to try to resolve it). I'm thus holding back on the code until I know that it at least would be useful for its initial purpose.
