### ISSUE TITLE
Query the Schema fields directly when iterating through them

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#32]
So far prevalent in the users, policy, & policy rules resources.

Schema fields are hardcoded (for example)
```
if _, ok := d.GetOk("email"); ok {
    template.Profile.Email = d.Get("email").(string)
}
```

We *should* be able to query the schema.ResourceData pointer to get the list of schema fields? that data type is not indexed tho.

**Comment by quantumew** [comment]
There is a schema for base user profile properties that does the type validation. As far as custom properties we have a generic `map[string]interface{}` that we send along to the API so I don't think this is relevant.
