### ISSUE TITLE
Add support for CORS trusted origins

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#33]
Add the base rise.com (and dev.rise.com) URLs to the list of trusted origins.

    Log into the Okta Admin Console with your Super-Admin account.
    Goto "API" > "Trusted Origins"
    Click the "Add Origin" button
    Fill out the fields & click save
        Name "Rise.com" (add "stage", "dev", etc if necessary)
        Origin URL "https://rise.com" (or "https://rise.zone" & "https://dev.rise.zone" on stage)
        CORS checked
        Redirect unchecked

**Comment by PurrBiscuit** [comment]
PR to add the `TrustedOrigins` things to the oktasdk go package -> https://github.com/articulate/oktasdk-go/pull/26
