### ISSUE TITLE
Resource okta_auth_server_policy_rule generates error

### ISSUE THREAD

**Issue by steven-1114** [articulate/terraform-provider-okta#333]
## Expected Behavior
When using the resource object "okta_auth_server_policy_rule" and running Terraform apply, the okta_auth_server_policy_rule should create the policy rule with the parameters specified and then report success.

## Actual Behavior
The policy rule is created correctly in Okta, but the resource reports failure with the message 'transport is closing'.  Hers is the ouput from the terraform apply:

okta_auth_server.example: Creating...
okta_app_oauth.example: Modifying... [id={...}]
okta_auth_server.example: Creation complete after 2s [id={...}]
okta_auth_server_policy.example: Creating...
okta_auth_server_scope.example: Creating...
okta_auth_server_policy.example: Creation complete after 2s [id={...}]
okta_auth_server_policy_rule.example: Creating...
okta_auth_server_scope.example: Creation complete after 2s [id={...}]
okta_app_oauth.example: Modifications complete after 4s [id={...}]

Error: rpc error: code = Unavailable desc = transport is closing

## Steps to Reproduce the Problem

Terraform V0.12.13, Okta Provider versions v3.0.32 and v3.0.34

Add the resources for:
 okta_auth_server (Completes Successfully)
 okta_auth_server_scope (Completes Successfully)
 okta_auth_server_policy (Completes Successfully)
 okta_auth_server_policy_rule (Adds rule successfully, but reports error)

## Additional info
Add any other context about the problem here (e.g. screenshots, links)
Here are the contents of my .tf file:
# Create: Okta Auth Server Scope 
resource "okta_auth_server_scope" "example" {
  auth_server_id   = "${okta_auth_server.example.id}"
  metadata_publish = "ALL_CLIENTS"
  name             = "example_token_name"
  description      = "Token"
  consent          = "IMPLICIT"
}

# Create: Okta Auth Server Policy
resource "okta_auth_server_policy" "example" {
  auth_server_id   = "${okta_auth_server.example.id}"
  status           = "ACTIVE"
  name             = "Default Policy"
  description      = "Default Policy"
  priority         = 1
  client_whitelist = ["ALL_CLIENTS"]
}

# Create: Okta Auth Server Policy Rule 
resource "okta_auth_server_policy_rule" "example" {
  auth_server_id       = "${okta_auth_server.example.id}"
  policy_id            = "${okta_auth_server_policy.example.id}"
  status               = "ACTIVE"
  name                 = "Default Rule"
  priority             = 1
  grant_type_whitelist = ["client_credentials"]
  scope_whitelist      = ["example_token_name"]
}

**Comment by quantumew** [comment]
@steven-1114 is there any way you can run that again with `TF_LOG=debug`? Remember to redact your auth token! This error appears to be a pretty generic one that has mislead me in the past.

**Comment by steven-1114** [comment]
Actually, it looks like I had missed the parameter for group_whitelist.   It worked when I added the data provider to get the okta_group "Everyone" and then added the id to the group_whitelist.

The documentation is misleading because the example references group_whitelist, and the Arguments references section includes scope_whitelist.  I misunderstood that and thought that all I needed was the scope_whitelist.

#Documentation link:
https://www.terraform.io/docs/providers/okta/r/auth_server_policy_rule.html

#This code worked fine
data "okta_group" "all" {
  name = "Everyone"
}
resource "okta_auth_server_policy_rule" "example" {
  auth_server_id       = "${okta_auth_server.example.id}"
  policy_id            = "${okta_auth_server_policy.example.id}"
  status               = "ACTIVE"
  name                 = "Default Rule"
  priority             = 1
  group_whitelist      = ["${data.okta_group.all.id}"]
  grant_type_whitelist = ["client_credentials"]
  scope_whitelist      = ["example_token_name"]
}

**Comment by quantumew** [comment]
@steven-1114  `scope_whitelist` and `group_whitelist` should both be in that arguments section. Thanks for calling that out, I will get the docs patched. I will also add a `Required: true` to any properties missing it here.

**Comment by steven-1114** [comment]
Thank you!
