### ISSUE TITLE
Retrieving user by id

### ISSUE THREAD

**Issue by quantumew** [articulate/terraform-provider-okta#336]
You can search for a user by id using:

```
data "okta_user" "example" {
  search {
    name = "id"
    value = "00ub0oNGTSWTBKOLGLNR"
  }
}
```

Having a shortcut would be nice, it would require diff suppression when it is computed:

```
data "okta_user" "example" {
  id = "00ub0oNGTSWTBKOLGLNR"
}
```

**Comment by brittanystoroz** [comment]
Hi there! Is this an issue I might be able to tackle? I am new to Terraform, Okta *and* Go 😂 But this looked like a nice, low-stakes way to get familiar with the technologies. Happy to submit a PR with a solution, but could probably use some guidance along the way!

**Comment by quantumew** [comment]
@brittanystoroz you bet, I think this a great one to dip into first. Feel free to give it a try and I can provide feedback or answer questions.

**Comment by brittanystoroz** [comment]
Hi! Here is where I'm at so far: https://github.com/brittanystoroz/terraform-provider-okta/commit/67a221d3d32b65275f25dab380a27fa9a773cd05

* I've added the ability to get a user by their ID by adding that schema to the okta user data source
* I've modified the `dataSourceUserRead` function to handle retrieving by `id` while keeping the `search` functionality in place

It looks like both `user` **and** `users` rely on this `userSearchSchema` -- in which case we would now want it to be optional for retrieving a single user, but still required when retrieving multiple users, yes? I'd like to be able to keep the reusability of that schema in place, but I'm a little stuck on finding a good way to conditionally set `Optional: true` vs. `Required: true`. Any thoughts on this?? Thanks for any help!

**Comment by quantumew** [comment]
Hey @brittanystoroz, I don't think in this case there is any problem with separating the schemas and adding them inline. Regardless making it dynamic is definitely possible with a function. Here is a pseudo code example:

```
func getUserSearchSchema(required bool) *schema.Schema {
    schema := &schema.Schema{
        ...schema
    }

    if required {
        schema.Elem.["<key>"].Required = true
    } else {
        schema.Elem.["<key>"].Optional = true
    }

    return schema
}
```

**Comment by brittanystoroz** [comment]
Ahhhh of course!! That makes perfect sense thank you. I will separate them out for now but remember that for future contributions.

I'm looking into suppressing the diff like you mentioned in the description and having a hard time nailing down my exact goal based on the documentation. I've been reading [here](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#diffsuppressfunc) and looking at examples in other provider repos for this particular use-case. It seems like the `id` would be a computed value that's only known after apply. In other repos I'm seeing the pattern of setting `Computed: true` but not adding in the `DiffSuppressFunc` for this type of argument.

I feel like my understanding is really fuzzy here -- are we trying to say "don't mark this resource as having changed when the ID property goes from not having a value (prior to apply) to having a value (after okta has generated it for us)"? In which case I'd be tinkering around with doing something along the lines of:

```go
DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
  return old == "" && new != ""
},
```

Let me know if I'm way off here/if there's other documentation I should be looking at, but no rush! I will keep researching in the meantime. Thanks for all your help!

**Comment by quantumew** [comment]
Hey @brittanystoroz, sorry missed your question, yea you have the right idea. `Computed: true` would be used when an attribute is computed in every case. In your case you want to be able to pass it an id or at times pass it search criteria and get an id back. I would recommend a new `Optional: true` attribute. `user_id` or something (this *won't* be sync'd in the read func). Doing this allows you to keep `id` computed without having to do diff suppression.
