### ISSUE TITLE
Document how to set "key_id" to retrieve pre-existing okta_app_metadata_saml resource

### ISSUE THREAD

**Issue by eliezio** [articulate/terraform-provider-okta#337]
The example at https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_app_metadata_saml/datasource.tf shows how to retrieve the metadata of okta_app_metadata_saml created by TF, by reusing output variables 'id' and 'key_id' from this resource. But in case we want to retrieve the metadata of a pre-existing resource, it's not clear what to put on the 'key_id' attribute.

Based on manual retrievals using HTTPie, I could confirm that for the Okta's "GET /api/v1/apps/${client_id}/sso/saml/metadata?kid=${key_id}" endpoint, you can omit the 'key_id' query parameter or you have to provide the exact value. But I also couldn't find any indication on how to get this parameter from Okta's API documentation.

Possible solutions I can think of:

1. In my particular case, making 'key_id' optional would solve the problem;
2. Document how to retrieve this attribute from a pre-existing resource.

**Comment by quantumew** [comment]
Interesting, Okta documents it as required but it is clearly not. I wonder if it is possible to have multiple "entities" on one app. Regardless there is a data source for retrieving your `kid`,  example below. 

```
data okta_app_saml app {
  label = "Me App"
}

data okta_app_saml_metadata meta {
  app_id = "${data.okta_app_saml.app.id}"
  kid       = "${data.okta_app_saml.app.kid}"
}
```

**Comment by eliezio** [comment]
You nailed it! Thanks @quantumew
