### ISSUE TITLE
Set target_id for profile mapping

### ISSUE THREAD

**Issue by jk-carroll** [articulate/terraform-provider-okta#340]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have several use cases where I need to specify the target_id for profile mapping, specifically I need to be able to map attributes from the org to an application which requires setting the target_id as the application id.

**Describe alternatives you've considered**
Extend the schema in the following resource
https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_okta_profile_mapping.go to allow the target_id to be set, rather than computed.

**Additional context**
https://developer.okta.com/docs/reference/api/mappings/#update-profile-mapping

* Make `target_id` required
* Add data source for resource mapping id (mostly for retrieving base user id

**Comment by quantumew** [comment]
@jk-carroll Thanks for opening this, should have something whipped up soon. Definitely should have implemented that off the bat!
