### ISSUE TITLE
Getting the default Okta's user schema ID

### ISSUE THREAD

**Issue by jralmaraz** [articulate/terraform-provider-okta#343]
Hi,

For profile mappings one common use case is to refer the source of the mapping as the Okta's default user schema.

At the moment we are manually retrieving the ID from here:

{{url}}/api/v1/user/types/default?expand=schema

Is there a way we would be able to fetch that ID to later on refer as a variable ? 

Let me know if the issue is not clear, just trying to figure a better way out (at the moment we are manually mapping a variable after getting the default's schema ID manually on the above URL :) ).

Cheers!

**Comment by quantumew** [comment]
Hey @jralmaraz,

I just added the `okta_user_profile_mapping_source`, which I think is what you are referring to. Here is a simple example using a Google IdP.

```
resource okta_profile_mapping test {
  source_id          = "${okta_idp_social.google.id}"
  target_id          = "${data.okta_user_profile_mapping_source.user.id}"

  mappings {
    id         = "login"
    expression = "appuser.email"
  }
}

resource okta_idp_social google {
  type          = "GOOGLE"
  protocol_type = "OAUTH2"
  name          = "testAcc_google_replace_with_uuid"

  scopes = [
    "profile",
    "email",
    "openid",
  ]

  client_id         = "abcd123"
  client_secret     = "abcd123"
  username_template = "idpuser.email"
}

data okta_user_profile_mapping_source user {}
```

**Comment by jralmaraz** [comment]
Thanks @quantumew ! That worked really well. @jk-carroll helped me testing that too :D
