### ISSUE TITLE
okta_app_secure_password_store does not satisfy okta API schema

### ISSUE THREAD

**Issue by the-maldridge** [articulate/terraform-provider-okta#347]
## Expected Behavior
I expect to be able to manage resources of type okta_app_secure_password_store.

## Actual Behavior

```
okta_app_secure_password_store.foo: Modifying... [id=some-id-was-here]

Error: The API returned an error: Api validation failed: publicAppInstance. Causes: errorSummary: Missing settings.signOn object
```
## Steps to Reproduce the Problem
Attempt to manage an app of this type.

**Comment by quantumew** [comment]
@the-maldridge Can you share your config with me? I can see that Okta's SDK is missing this property on this app type (link below). I'd like to add a test to our acceptance tests for this scenario.

https://github.com/okta/okta-sdk-golang/blob/master/okta/securePasswordStoreApplicationSettings.go#L24-L27

**Comment by the-maldridge** [comment]
Sure, here's an example app from my terraform project:

```
resource "okta_app_secure_password_store" "boast" {
  label = "Boast"
  url = "https://secure.boast.io/users/sign_in"
  password_field = ""
  username_field = ""
  credentials_scheme = "SHARED_USERNAME_AND_PASSWORD"
  shared_username = "vendor-boast+nonadmin@<redacted>"
}
```

I think this is what you were asking for, but if you need more don't hesitate to ask.

**Comment by quantumew** [comment]
@the-maldridge Thanks! Opened a PR with this test case but it works in my tenant. I also checked their docs, there is no mention of the `signOn` object on the secure password store app. There is some undocumented behavior happening here that is not happening in my tenant. We may have to chat with Okta on this one.

**Comment by the-maldridge** [comment]
That's spooky, but I wouldn't be surprised if Okta has some kind of undocumented breaking change in a public API.  I can provide a terraform debug trace if that would help, but I'd rather not post that to github.

**Comment by quantumew** [comment]
@the-maldridge I see it occasionally with features that are flipped on for you but not for our test tenant. Apropos the debut log, understandable, a lot to redact in this case. Regardless I don’t think it would help much.

The one thing that would help is if you created one of these apps in your tenant via the API and posted the body it returns. Based on that we might be able to make some inferences on what it needs. Up to you, opening a ticket with Okta would work too.

**Comment by the-maldridge** [comment]
Sure, I can do that and report back.  Do you want it created purely with the API, i.e. I write a shim in Go to drive it, or do you want me to create a new app with terraform and try that?

**Comment by quantumew** [comment]
@the-maldridge honestly I was thinking of just throwing it in postman/curl and getting it created. Give it an empty signOn object to see if it gives you more details about what settings are missing. See if we can gather what it needs. Worth a try we can open a ticket if we cannot gather any more info.

**Comment by the-maldridge** [comment]
Just wanted to comment that I haven't forgotten this one but I'm out at AWS re:invent this week so I don't think I'll have time to run the test.

**Comment by the-maldridge** [comment]
Time has gotten away from me.  @cpiwarski is going to handle followup here on my behalf.

**Comment by cpiwarski** [comment]
Hello @quantumew, using curl I was able to make a SWA app. I then removed the signOn object and was left with a generic error: "The settings.signOn object doesn't match the type indicated by signOnMode value or is ill defined"

**Comment by quantumew** [comment]
hah that doesn't help much Okta! What happens with an empty `signOn` object @cpiwarski? Does it give you any specific attributes that are missing?

**Comment by cpiwarski** [comment]
@quantumew With an empty sign on object in the settings, I am served the same error.
