### ISSUE TITLE
Missing attribute to create group claims for Okta-Mastered groups

### ISSUE THREAD

**Issue by kevin-chiu-dragon** [articulate/terraform-provider-okta#355]
According to [Create a Groups Claim for Okta-Mastered Groups](https://developer.okta.com/docs/guides/create-token-with-groups-claim/create-groups-claim/#create-a-groups-claim-for-okta-mastered-groups), ones should be able to create a groups claim on an OIDC client application.

The corresponding config is not in [okta_app_oauth](https://www.terraform.io/docs/providers/okta/r/app_oauth.html), and
seems this is also missing from Okta public API (but not sure, seems not in [Add OAuth 2.0 Client Application](https://developer.okta.com/docs/reference/api/apps/#add-oauth-2-0-client-application)).

**Comment by jralmaraz** [comment]
Hi @kevin-chiu-dragon, can you try something similar as the below resource ? Is that something similar to what you are looking for ? 


resource "okta_auth_server_claim" "Views" {
  auth_server_id    = "${okta_auth_server.Member_Portal.id}"
  name              = "Experience"
  status            = "ACTIVE"
  claim_type        = "RESOURCE"
  value_type        = "GROUPS"
  group_filter_type = "REGEX"
  value             = "groups: matches regex .*portalMembers_.*"
  scopes            = ["Member_Scope"]
  depends_on        = ["okta_auth_server_scope.Member_Scope"]
}

**Comment by kevin-chiu-dragon** [comment]
Hi @jralmaraz , thanks for the suggestion, yes we've tried the above with dev okta account and it works. But since it needs additional licensing and the OIDC client application groups claims can serve our needs, so we are trying to use the later.

**Comment by jralmaraz** [comment]
Nice, thanks for confirming that @kevin-chiu-dragon. 

I could see any that profile is available in the resource: https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_okta_app_oauth.go

			"profile": &schema.Schema{
				Type:        schema.TypeString,
				StateFunc:   normalizeDataJSON,
				Optional:    true,
				Description: "Custom JSON that represents an OAuth application's profile",

Based on the doc ["Create Token with group claims"](https://developer.okta.com/docs/guides/create-token-with-groups-claim/add-list-of-groups/) I have created the following resource:

resource "okta_app_oauth" "testoidc" {
  status         = "ACTIVE"
  label          = "testoidc"
  type           = "web"
  grant_types    = ["implicit", "authorization_code"]
  redirect_uris  = ["https://placeholder.com"]
  post_logout_redirect_uris = ["https://placeholder.com"]
  response_types = ["code", "token", "id_token"]
  profile = jsonencode({"groupwhitelist"=["00g1xnmx8g7WIAVku357"]})
}

The debug code showed the profile section being passed correctly and the resource was created, but the group filter wasn't there even though the resource got created. I might have misunderstood the doco and will go through it again. Just sharing the details here for information.

2019-11-25T15:03:31.828+1100 [DEBUG] plugin.terraform-provider-okta_v3.0.33_x4:  "profile": {
2019-11-25T15:03:31.828+1100 [DEBUG] plugin.terraform-provider-okta_v3.0.33_x4:   "groupwhitelist": [
2019-11-25T15:03:31.828+1100 [DEBUG] plugin.terraform-provider-okta_v3.0.33_x4:    "00g1xnmx8g7WIAVku357"
2019-11-25T15:03:31.828+1100 [DEBUG] plugin.terraform-provider-okta_v3.0.33_x4:   ]
2019-11-25T15:03:31.828+1100 [DEBUG] plugin.terraform-provider-okta_v3.0.33_x4:  },


From an UI API call perspective, the following was what I could inspect, but its the internal API unfortunately:

Request Method: POST

Request URL: https://instance.okta.com/api/v1/internal/apps/0oa6o6isarIXUX8hQ3l5/settings/oauth/idToken?issuerHint=true

{"valueType":"GROUPS","groupFilterType":"STARTS_WITH","instanceId":"0oa6o6isarIXUX8hQ3l5","issuer":"https://instance.okta.com","orgUrl":"https://instance.okta.com","customUrl":"https://instance-custom.domain.xyz","audience":"0oagwrvmvkbjUkEDm0h7","issuerMode":"ORG_URL","name":"groups","value":"test"}

**Comment by jralmaraz** [comment]
https://github.com/articulate/terraform-provider-okta/commit/d6ef132faf7a31bc56e9e58e1c8ef12d444727b0#diff-2bf37877a9890a57960ab5fb1558261a

https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_app_oauth/group_for_groups_claim.tf

Had a look at the above I tried the following resource (also changed the ID for an existing group name, :

```
resource "okta_app_oauth" "testoidc" {
  status         = "ACTIVE"
  label          = "testoidc"
  type           = "web"
  grant_types    = ["implicit", "authorization_code"]
  redirect_uris  = ["https://placeholder.com"]
  post_logout_redirect_uris = ["https://placeholder.com"]
  response_types = ["code", "token", "id_token"]
  profile = <<JSON
   {
    "groups": {
      "whitelist": [
          "00g1xnmx8g7WIAVku357"
        ]
    }
  }
JSON
}

```

Also tried the following without success (group resource in the same file):

```
resource "okta_group" "whitelist_group" {
  name = "test"
}

resource "okta_app_oauth" "testoidc" {
  status         = "ACTIVE"
  label          = "testoidc"
  type           = "web"
  grant_types    = ["implicit", "authorization_code"]
  redirect_uris  = ["https://placeholder.com"]
  post_logout_redirect_uris = ["https://placeholder.com"]
  response_types = ["code", "token", "id_token"]
  profile = <<JSON
   {
    "groups": {
      "whitelist": [
          "${okta_group.whitelist_group.name}"
        ]
    }
  }
JSON
}

Just to be clear, we're talking about this setting ? Cheers!

![image](https://user-images.githubusercontent.com/13877691/69513012-76c19600-0f9a-11ea-9503-95583b85b247.png)


```

**Comment by jralmaraz** [comment]
The profile details are though correctly set and returned when doing a GET apps:

{{url}}/api/v1/apps/0oa1xo30chxtUVbQ4357

![image](https://user-images.githubusercontent.com/13877691/69513338-9ad1a700-0f9b-11ea-9c59-d864090c317d.png)

**Comment by jralmaraz** [comment]
Can you test retrieving the actual token flows to see if the group will be seen ?

**Comment by kevin-chiu-dragon** [comment]
Yes, it's the OpenID Connect ID Token setting. While instead of group whitelist, we need to create a groups claim:

![image](https://user-images.githubusercontent.com/53592724/69515319-2c83e900-0f89-11ea-90f3-76e02a0dc727.png)

**Comment by jralmaraz** [comment]
@quantumew do you think this call is only internal and we might need to reach to Okta ? 

Let me know what would be the next step, happy to chase.

Cheers.

Request Method: POST

Request URL: https://instance.okta.com/api/v1/internal/apps/0oa6o6isarIXUX8hQ3l5/settings/oauth/idToken?issuerHint=true

{"valueType":"GROUPS","groupFilterType":"STARTS_WITH","instanceId":"0oa6o6isarIXUX8hQ3l5","issuer":"https://instance.okta.com","orgUrl":"https://instance.okta.com","customUrl":"https://instance-custom.domain.xyz","audience":"0oagwrvmvkbjUkEDm0h7","issuerMode":"ORG_URL","name":"groups","value":"test"}

**Comment by jralmaraz** [comment]
This was the response I got from Support, so, it cannot be done through the public API yet :(

At the moment, we do not provide an option to configure the groups claim for OIDC applications through the public API either in the creation process or after it. The administrative panel interface uses an internal API to submit the changes.

You can find below a few examples on how to configure the groups claim through the internal API. Please note that, because this are internal API requests, the body might be changed by engineering without any prior notice.

1. Filtering on groups claim using regular expression
curl -X POST \
  'https://{{okta_subdomain}}/api/v1/internal/apps/{{app_id}}/settings/oauth/idToken?issuerHint=true' \
  -H 'Accept: application/json \
  -H 'Authorization: SSWS {{api_token}}' \
  -H 'Content-Type: application/json' \
  -d '{
    "valueType": "GROUPS",
    "groupFilterType": "REGEX",
    "instanceId": "{{app_id}}",
    "issuer": "https://{{okta_subdomain}}",
    "orgUrl": "https://{{okta_subdomain}}",
    "customUrl": null,
    "audience": "{{app_id}}",
    "issuerMode": "ORG_URL",
    "name": "{{group_claim}}",
    "value": "{{regular_expression}}"
}'

2. Filtering on groups claim using starts with/equals/contains
curl -X POST \
  'https://{{okta_subdomain}}/api/v1/internal/apps/{{app_id}}/settings/oauth/idToken?issuerHint=true' \
  -H 'Accept: application/json \
  -H 'Authorization: SSWS {{api_token}}' \
  -H 'Content-Type: application/json' \
  -d '{
    "valueType": "GROUPS",
    "groupFilterType": "STARTS_WITH", // or EQUALS, or CONTAINS
    "instanceId": "{{app_id}}",
    "issuer": "https://{{okta_subdomain}}",
    "orgUrl": "https://{{okta_subdomain}}",
    "customUrl": null,
    "audience": "{{app_id}}",
    "issuerMode": "ORG_URL",
    "name": "{{group_claim}}",
    "value": "{{value}}"
}'

3. Filtering on groups claim using an Okta expression
curl -X POST \
  'https://{{okta_subdomain}}/api/v1/internal/apps/{{app_id}}/settings/oauth/idToken?issuerHint=true' \
  -H 'Accept: application/json \
  -H 'Authorization: SSWS {{api_token}}' \
  -H 'Content-Type: application/json' \
  -d '{
    "valueType": "GROUPS",
    "groupFilterType": "STARTS_WITH", // in this specific use-case, the value is not relevant
    "instanceId": "{{app_id}}",
    "issuer": "https://{{okta_subdomain}}",
    "orgUrl": "https://{{okta_subdomain}}",
    "customUrl": null,
    "audience": "{{app_id}}",
    "issuerMode": "ORG_URL",
    "name": "{{group_claim}}",
    "value": "{{expression_value}}"
    "valueType": "EXPRESSION"
}'

**Comment by kevin-chiu-dragon** [comment]
@jralmaraz thanks for the investigation and update! Looks like we need to stick with manual steps for the time being.

**Comment by jralmaraz** [comment]
No problem, I have also raised a feature request for this so we can at least chase and follow it up:

https://ideas.okta.com/app/#/case/113869

**Comment by shaoliang-jia-dragon** [comment]
Any update on this issue?
