### ISSUE TITLE
The option to set an auth server policy rule user to "any user assigned the app"

### ISSUE THREAD

**Issue by evanger24** [articulate/terraform-provider-okta#357]
When using the okta_auth_server_policy_rule resource, I want to be able to set my user to any user assigned to the app instead of having to create an okta_group and set the user to "assigned the app and a member of one of the following": <okta_group>. 

Based on the example given the group_whitelist value in the resource "okta_auth_server_policy_rule" is set to a data source named "data group".  However, I just want the user to be any user assigned to the application. 

```
data "okta_group" "all" {
  name = "Everyone"
}

resource "okta_auth_server_policy_rule" "test" {
  auth_server_id       = "${okta_auth_server.test.id}"
  policy_id            = "${okta_auth_server_policy.test.id}"
  status               = "ACTIVE"
  name                 = "test"
  priority             = 1
  group_whitelist      = ["${data.okta_group.all.id}"]
  grant_type_whitelist = ["implicit"]
}
```

Is there a way to not specify a group_whitelist but also be able to specify the grant_type_whitelist to implicit, authorization_code, password, and client_credentials? There is nothing in Okta that prevents this.

**Comment by jralmaraz** [comment]
Myself and @jk-carroll had the same doubt the other day.

If you inspect the browser's response while listing the policies/rules, the option for "Any user assigned the app" Returns the following condition:

`"conditions":{"people":{"users":{"include":[],"exclude":[]},"groups":{"include":["EVERYONE"]...`

So if you try the following, it should do the trick:

`group_whitelist      = ["EVERYONE"]`

Let us know how it goes.

**Comment by evanger24** [comment]
Works like a charm! Thanks for the explanation & work around!

**Comment by rachrdfds** [comment]
This should be in the official documentation (https://www.terraform.io/docs/providers/okta/r/auth_server_policy_rule.html) so you don't have to find the answer in a GitHub issue, IMHO.
