### ISSUE TITLE
okta_app_saml resource will delete any group assignments created by okta_app_group_assignment

### ISSUE THREAD

**Issue by ryno75** [articulate/terraform-provider-okta#359]
## Expected Behavior
1. Create an AWS SAML application using `okta_app_saml` resource from module1
2. Add AD to IAM group/role mappings to the SAML application using the `okta_app_group_assignment` resource in module2 (a 2nd module is required because there are manual steps required to add AWS Access Keys to Okta, Configure IAM SAML IDP & roles, Sync AD and IAM to Okta)
3. Run an `apply` against module1 after step 2 without it affecting the group assignments.
## Actual Behavior
1. Create an AWS SAML application using `okta_app_saml` resource from module1
2. Add AD to IAM group/role mappings to the SAML application using the `okta_app_group_assignment` resource in module2
3. Running an `apply` on module1 after step 2 has been run will remove the group assignments
e.g.
```
      ~ groups                     = [
          - "00g6r2m5i3oQH6Ygu1t7",
          - "00g7p46yp8FtfDSR31t7",
          - "00g973myhziBIxoVX1t7",
          - "00gc0ti1hq5dzpyhf1t7",
          - "00gc0ti1hsBNBWaKi1t7",
          - "00gc0ti1humT0bYuE1t7",
          - "00gc0ti1hya0JlNYG1t7",
        ]
```
## Steps to Reproduce the Problem
See `Actual Behavior` above.
This behavior is witnessed with:
- Terraform v0.12.12 and v0.12.16
- Okta provider versions: 3.0.28, 3.0.34, and 3.0.38

**Comment by ryno75** [comment]
What's strange to me is that `okta_app_saml` is even trying to manage `groups` since it no longer has any notion of that property in the resource code.

**Comment by quantumew** [comment]
@ryno75 I think you are running into #322. i.e. the legacy way of managing groups needs to be lifecycle ignored until the work to deprecate this is done #248. See example here: https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_app_group_assignment/basic.tf

**Comment by ryno75** [comment]
> @ryno75 I think you are running into #322. i.e. the legacy way of managing groups needs to be lifecycle ignored until the work to deprecate this is done #248. See example here: https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_app_group_assignment/basic.tf

Ah, see this is what I get for only searching "open" issues. dangit!
Thanks for the quick reply on the workaround!
implementing this now...
```hcl
  lifecycle {
    ignore_changes = ["users", "groups"]
  }
```
