### ISSUE TITLE
okta_auth_server_policy plans correctly but fails on execution with 'conditions.clients.include: Resource not found'

### ISSUE THREAD

**Issue by rachrdfds** [articulate/terraform-provider-okta#360]
## Expected Behavior
Create an access policy for an auth server with 'Assigned to clients = a specific group'

## Actual Behavior
Terraform plans correctly but fails on the execution:
![image](https://user-images.githubusercontent.com/57186882/69966793-6c157c80-1517-11ea-8785-7297d2dbe3f7.png)

## Steps to Reproduce the Problem
`Create an Auth server:
resource okta_auth_server auth_server_selfservice {
  name						= "CustomerIAM.SelfService (Terraform)"
  description				= "Used for the Customer Identity And Access Managment Self-service"
  audiences					= ["api://CustomerIAM.SelfService"]
  credentials_rotation_mode	= "AUTO"
  issuer_mode				= "CUSTOM_URL"
  status					= "ACTIVE"
}

Create an application:
resource okta_app_oauth app_oauth_selfservice_swagger {
  label                      = "CustomerIAM.SelfService.Swagger"
  type                       = "browser"
  grant_types                = ["implicit"]
  redirect_uris              = ["https://localhost:5001/swagger", "https://localhost:5001/swagger/oauth2-redirect.html"]
  login_uri					 = "https://localhost:5001/swagger"
  post_logout_redirect_uris	 = ["https://localhost:5001/swagger"]
  response_types             = ["token", "id_token"]
  token_endpoint_auth_method = "none"
  custom_client_id			 = "0oa9uixyf9Jx3FKaR0x6"
  issuer_mode				 = "CUSTOM_URL"
}

Create an auth server policy pointing to the application:
resource okta_auth_server_policy auth_server_policy_selfservice {
  auth_server_id   = "${okta_auth_server.auth_server_selfservice.id}"
  status           = "ACTIVE"
  name             = "CustomerIAM.SelfService"
  description      = "CustomerIAM.SelfService (Terraform)"
  priority         = 1
  client_whitelist = ["${okta_app_oauth.app_oauth_selfservice_swagger.id}"]
  #client_whitelist = ["ALL_CLIENTS"]
}
`
As can be seen in the execution plan there are no issues setting the client_whitelist = ALL_CLIENT, and there are no issues doing this manually (using the GUI):
![image](https://user-images.githubusercontent.com/57186882/69967193-31601400-1518-11ea-8bb7-8fbbfa52208b.png)

Let me know if there are details missing or any other things that I should provide to help locating and fixing the issue.

**Comment by quantumew** [comment]
@rachrdfds It looks like you're assigning a `custom_client_id`. IIRC, this means you will want to do this: `client_whitelist = ["${okta_app_oauth.app_oauth_selfservice_swagger.client_id}"]`. Use `client_id` as opposed to `id`. Let me know if this works. I will leave this ticket open to update the docs to make this distinction more clear.

**Comment by rachrdfds** [comment]
@quantumew point taken and your suggestion is right. This 'issue' can be closed whenever you feel like it :-) Thanks.

**Comment by noinarisak** [comment]
Closed, per last comments by @rachrdfds .
