### ISSUE TITLE
Sometimes 'produced an unexpected new value occurs' when creating lots of new objects

### ISSUE THREAD

**Issue by rachrdfds** [articulate/terraform-provider-okta#362]
## Expected Behavior
Creation of ne Okta objects without any issues

## Actual Behavior
Sometimes when I destroy and try to recreate new objects in Okta, I get a 'provider "okta" produced an unexpected new value for was present, but now absent error'.

See the first video, where you see:
- destoy all Terraform managed objects in Okta
- apply terraforming that generates correct plan and then starts execution the plan
- getting the error
![image](https://user-images.githubusercontent.com/57186882/70144225-c04a6900-169d-11ea-9d40-234ae8238525.png)

Second video shows that when running the apply again, then this is fixed and everything is ok:

[2019-12-04_13h56_23.zip](https://github.com/articulate/terraform-provider-okta/files/3921892/2019-12-04_13h56_23.zip)

## Steps to Reproduce the Problem
Create new Okta objects

## Additional info
Is this because the Terraforming is done too quickly so the all the new changes has not settled before Terraform tries to do new things?

**Comment by noinarisak** [comment]
Hi @rachrdfds. Just taking a stab at this. 

Is this happening every time? Could you supply an example of your terraform script that is causing this? A trace log with `TF_LOG=TRACE` would also be helpful to see if it is bug. More details on [TF_LOG](https://www.terraform.io/docs/internals/debugging.html).

**Comment by rachrdfds** [comment]
Actually, it used to only happen sometimes, but now I have just applied and destructed five times and none succeeded. 

I have attached a zip with three traces.
- trace with one inconsistency error
- trace with one inconsistency error and then a successfull reapply
- trace with two inconsistency errors

It is the same configuration that is used every time

[TF failing with two inconsistency errors .zip](https://github.com/articulate/terraform-provider-okta/files/3925747/TF.failing.with.two.inconsistency.errors.zip)

**Comment by noinarisak** [comment]
Hi @rachrdfds.

Just getting back to your issue. After reviewing your logs. Thanks by the way! 

I seen something similar to this when I was working on `okta_app_user_schema` where I was also getting the `Provider produced inconsistent result after apply` error message. In my case, I was creating multiple app_user_schema objects in my tf script and the Okta API Endpoint which I believe was overwriting concurrent changes that conflicted with terraform default 10 concurrent operation to walk the graph (state). With out changing my code I was able to test with following option

`-parallelism=1`: more details [here](https://www.terraform.io/docs/commands/apply.html#parallelism-n).

In the end, I followed @quantumew recommendation and implemented a workaround using `depend_on` on each of `app_user_schema` resources in my tf scripts on except for the first `app_user_schema` resource.

[Here](https://github.com/articulate/terraform-provider-okta/issues/302#issuecomment-542661206) the issue thread for more details.

From your logs it looks like you have more them one `user_schema`. Could you try the above and let us know.

**Comment by rachrdfds** [comment]
Hi @noinarisak.

Thanks for your feedback. I like parallelism, so I have implemented the depends_on method and it works like charm :-)

Now I'm using this (depends_on) on other resources too as it makes the configuration/execution more robust. 

If this is a general 'issue' regarding trying to create too many objects too fast, it should be considered to document this somewhere.

**Comment by noinarisak** [comment]
Hi @rachrdfds,

Glad that worked out for you!

Maybe @quantumew would consider verbiage (ie. Warning: section) on the publish documentation at https://www.terraform.io/docs/providers/okta/d/user.html so the next persons are aware of the workaround. =)
