### ISSUE TITLE
Inconsistent handling of group assignments for application

### ISSUE THREAD

**Issue by rachrdfds** [articulate/terraform-provider-okta#363]
## Expected Behavior
Group assigned on applications stays assigned.

## Actual Behavior
If I create all the Okta objects using Terraform including group assignments (okta_app_group_assignment) then the there are issue regarding keeping the groups assigned to an application. It keeps wanting to assign the group, but it never really gets assigned.

## Steps to Reproduce the Problem
Application creation:
`resource okta_app_oauth app_oauth_selfservice_swagger {
  label                      = "CustomerIAM.SelfService.Swagger"
  type                       = "browser"
  grant_types                = ["implicit"]
  redirect_uris              = "${var.selfservice_swagger_redirect_uris}"
  login_uri					 = "${var.selfservice_swagger_login_uri}"
  post_logout_redirect_uris	 = "${var.selfservice_swagger_post_logout_redirect_uris}"
  response_types             = ["token", "id_token"]
  token_endpoint_auth_method = "none"
  issuer_mode				 = "CUSTOM_URL"
}

resource okta_app_oauth app_oauth_selfservice_client {
  label                      = "CustomerIAM.SelfService.Client"
  type                       = "service"
  grant_types                = ["client_credentials"]
  response_types             = ["token"]
}

resource okta_app_oauth app_oauth_selfservice_integrationtest {
  label                      = "CustomerIAM.SelfService.IntegrationTest"
  type                       = "service"
  grant_types                = ["client_credentials"]
  response_types             = ["token"]
}`

Group creation:
`resource okta_group group_selfservice_swagger_customer {
  name			= "CustomerIAM.SelfService.Swagger.Customer (Terraform)"
  description	= "CustomerIAM.SelfService.Swagger.Customer (Terraform)"
}`

Group assingments:
`resource okta_app_group_assignment group_assignment_selfservice_swagger_customer {
  app_id   = "${okta_app_oauth.app_oauth_selfservice_swagger.id}"
  group_id = "${okta_group.group_selfservice_swagger_customer.id}"
}`

See the attached video, where you will see:
- show there are two manually created applications
- run destroy (for the second time) to confirm that there are no Terraform managed objects
- run apply to create 27 resources (this time without any errors regarding in the contrary to other issue, where objects looks like to be created too fast)
- in Okta refresh application list to show the new applications
- in Okta go into application and show two group assignments
- run apply again that shows four changes
- scroll thru the Terraform changes that show (among other things)
-- changes to group assignments for the application
-- change of Authz server priority from 2 -> 1 (why?)
-- group membership changes
- in Okta refresh application and show only one group assignment
- run apply again that shows one add and 2 changes
- scroll thru the Terraform changes that show (among other things)
-- create new group assignment for the application
-- changes to group assignments for the application (because of the above)
-- change of Authz server priority from 2 -> 1 (again why?)
-- group membership changes
- in Okta refresh application and show only one group assignment
- run apply again that shows the same addition and changes above (and then we are in a never ending loop).

Is the group assignments done wrong? It is the same group assignment that keeps 'failing'.
Do you need other informations/videos etc.?

[2019-12-04_14h31_26.zip](https://github.com/articulate/terraform-provider-okta/files/3922058/2019-12-04_14h31_26.zip)

## Additional info
Add any other context about the problem here (e.g. screenshots, links)

**Comment by quantumew** [comment]
Can you confirm you are not running into #359? Still have an open PR with Hashicorp to get the docs updated. On hold currently.

**Comment by rachrdfds** [comment]
If this (https://www.terraform.io/docs/providers/okta/r/app_saml.html) is what you mean, then I can confirm that okta_app_saml is not being used at all.

I haven't implemented this yet, is that the current workaround to use?
`lifecycle {
    ignore_changes = ["users", "groups"]
  }
`
It looks like it is not only specific for okta_app_saml but perhaps for apps in general? 
Would the legacy way of assigning groups to apps or the above lifecycle method be best?

**Comment by quantumew** [comment]
@rachrdfds Yea not app specific, this applies to all apps. The `users` and `groups` attributes will be deprecated, once someone gets around to #248, so I would recommend the approach you are using + the lifecycle ignore.

**Comment by rachrdfds** [comment]
Cool thanks, I will do that.
Keep up the good work, it is really appreciated :-)

**Comment by rachrdfds** [comment]
Using the lifecycle-method helps regarding the group assignments, but I still see consistent 'mishandling'/interpretation of priority of group assignments (and Auth server):
![image](https://user-images.githubusercontent.com/57186882/70150365-3228af80-16aa-11ea-8f47-e9aae975268a.png)
[2019-12-04_15h25_55.zip](https://github.com/articulate/terraform-provider-okta/files/3922307/2019-12-04_15h25_55.zip)

So I should add "priority" to the lifecycle list as well?

**Comment by rachrdfds** [comment]
hmmm, but that can't be done :-(
![image](https://user-images.githubusercontent.com/57186882/70150747-c85cd580-16aa-11ea-851c-6fad0120da8a.png)

**Comment by quantumew** [comment]
You are ignoring changes to `priority` on the wrong resource. For the priority on `okta_app_group_assignment`, you can simply remove it from your config, Okta's API appears to be ignoring your value. As for the auth server policy priority, Okta is pretty fast and loose with these, for instance, if you send it `1` and it cannot move it to the top priority, Okta will dynamically set it to a dynamic priority.

**Comment by rachrdfds** [comment]
I actually don't have priority on okta_app_group_assignment:
![image](https://user-images.githubusercontent.com/57186882/70151913-8af94780-16ac-11ea-8736-0dc00a0a4087.png)

I can try to set it explicit and see if that helps.

Regarding auth server, I do set it to 1, but I'm not allowed to remove the attribute from the config:
![image](https://user-images.githubusercontent.com/57186882/70152145-fa6f3700-16ac-11ea-8398-2f5cc701080c.png)

if I comment it out:
![image](https://user-images.githubusercontent.com/57186882/70152171-05c26280-16ad-11ea-873f-1ae56fa0bf26.png)

I end up with:
![image](https://user-images.githubusercontent.com/57186882/70152215-1bd02300-16ad-11ea-955f-b1398fdd2b60.png)

**Comment by quantumew** [comment]
Yea for some reason it appears Okta is updating it to 2 thus the perpetual diff on the auth server policy. Ah I see, I bet Okta is defaulting the group membership priority to 1. The provider should do the same.

https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_okta_app_group_assignment.go#L57-L60

**Comment by rachrdfds** [comment]
Inserting the ignore of priority for group assignments 'removes' the changes regarding those:
![image](https://user-images.githubusercontent.com/57186882/70153367-1d024f80-16af-11ea-80c2-3ed3b0033f34.png)

I still wuite understand why in the first place these 'changes' happen when I don't set them explicit, but at least I have a work around for it.

Thanks :-)

**Comment by quantumew** [comment]
Yea this would be Okta's API doing making some dynamic changes. There are various reasons for this. For instance, two policies both with overlapping priorities, one will get dynamically dropped down by Okta. The other one, is Okta adding a default the provider isn't assigning but should! Thanks!
