### ISSUE TITLE
Add IdP metadata URL attribute to okta_app_saml resource

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [articulate/terraform-provider-okta#364]
**Is your feature request related to a problem? Please describe.**

Currently, the **okta_app_saml** Terraform resource has a `metadata` output attribute but doesn't have an attribute related to Identity provider metadata URL that can be useful for applications that support dynamic SAML configuration.
![Screenshot 2019-12-05 at 4 21 47 PM](https://user-images.githubusercontent.com/55390366/70243508-5e603100-177b-11ea-8be1-9b8bbe37a81e.png)

**Describe the solution you'd like**

Additional attribute for **okta_app_saml** resource with the name like `metadata_url` that can be used in further activities or as modules output.

**Additional context**
Actually it can be defined by the following example,
```hcl
"https://${okta_org_name}.${okta_base_url}/app/${entity_key}/sso/saml/metadata"
```

**Comment by quantumew** [comment]
Hey @ivan-sukhomlyn, we could definitely add the link to the attrs. Just an FYI there is a metadata data source for SAML apps in case that is helpful.

**Comment by ivan-sukhomlyn** [comment]
Hello @quantumew 
Yes, I know. Thanks!
But I saw SAML feature realization at some applications where only dynamic configuration supports and the metadata URL is required.
