### ISSUE TITLE
okta_app_saml has a default set for key_years_valid

### ISSUE THREAD

**Issue by AClarkie** [articulate/terraform-provider-okta#365]
I'm confused why the key_years_valid parameter has a default in the terraform but when created via the UI does not have a default set:
https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_okta_app_saml.go

Steps to reproduce:
1) Create a saml app via the UI
2) Import the app into the terraform state
3) Run terraform plan

This is will suggest the object needs to be updated in place with the key_years_valid parameter set.

**Comment by quantumew** [comment]
Yea, that seems wrong. Should be an easy fix. Thanks for calling it out.

**Comment by jralmaraz** [comment]
Hi @quantumew , should we just remove the default in this case ? 

Cheers.

**Comment by quantumew** [comment]
@jralmaraz likely, I would also be interested to know the effect on the config if someone created a SAML app with an old version of the provider and updated. I would want to make sure there wasn’t an adverse effect that would require attention.
