### ISSUE TITLE
Ability to assign specific group targets to a user assigned USER_ADMIN admin role.

### ISSUE THREAD

**Issue by anyeone** [articulate/terraform-provider-okta#366]
**Is your feature request related to a problem? Please describe.**
I am trying to create a service account that has USER_ADMIN role only for the groups I have created for the app I am creating through the script (not all groups in my instance).  

This is supported via Okta API:  https://developer.okta.com/docs/reference/api/roles/#group-administrator-role-group-targets ;  users that have USER_ADMIN permission for specific groups MUST assign one of these groups as part of the user creation step, whereas users that have USER_ADMIN permission without target group scope can create a user outside of groups or for any group. See  https://developer.okta.com/docs/reference/api/users/#create-user-in-group

Currently, I can use terraform-provider-okta to generate the user and give them USER_ADMIN role, or to add them to a group that I have granted USER_ADMIN role using the okta_group_roles resource, but I do not see any way to target a user or group's USER_ADMIN permissions to specific groups as described in that API link through terraform.

**Describe the solution you'd like**
Create a generic resource that grants a user a specified adminrole, scoped to specific groups:
resource okta_user_adminrole_groups {
    userid = "{userid}"
    adminrole = "USER_ADMIN"
    groups = ["{groupid}>","{groupid2}"...]
}

**Describe alternatives you've considered**
1) . Enhance okta_user resource to make the adminroles property more verbose in specifying which groups are assigned to each role: ie.
adminroles = [ { "USER_ADMIN": ["{group1}","{group2}"]} , 
                         { "OTHERADMIN" : [ALL] }
                       ]
I think this option is not ideal because it makes the syntax really clunky and nested to keep track of which admin roles need which groups all in the context of another entity.

2) Create new resource okta_user_groupadmin_groups that explicitly makes a user a USER_ADMIN and assigns them to the groups provided:
resource okta_user_groupadmin_groups {
    userid = "{userid}"
    groups = ["{group1id}","{group2id}"]
}
(better than #1 , and does solve my specific problem, but does not address other types of adminrole that can be limited by group)

3) Enhance the okta_group_roles to have a role_group_targets element:
resource "okta_group_roles" "example" {
  group_id    = "{groupid}"
  admin_roles = ["USER_ADMIN"]
  role_group_targets = ["{targetgroupid1}","{targetgroupid2}",...]
}
Again this might get complicated if you have a group that has multiple admin roles with differential group targets, I think it's better to have a specific resource for each user/adminrole combination if that is possible.

**Additional context**
n/a

**Comment by tgoodsell-tempus** [comment]
I think based on the API your 3rd option would be best, though I suppose due to TF provider methods doing a for loop on the list of roles; the API itself has a 1 to 1 mapping for groups/users to admin roles with unique id for each assignment; then maybe a good compromise would be optional attributes in the schema for each role type which accepts groups. 

Something like "user_admin_groups" and "help_desk_admin_groups".

Then we'd just have to modify the code so that when those two role types are being assigned, it will detect if those attributes are used and then do the follow up group assignment actions documented in:
https://developer.okta.com/docs/reference/api/roles/#add-group-target-to-group-administrator-role

**Comment by mikemcowie** [comment]
Definitely want to have, as looking at automating some implementation of okta, and this would be a requirement to be able to use terraform to do so...

**Comment by chriskolenko** [comment]
+1

**Comment by tgoodsell-tempus** [comment]
Hey Y'all, please see https://github.com/terraform-providers/terraform-provider-okta/issues/13 since the provider has moved there.
