### ISSUE TITLE
Schemas: add support to edit a base user subschema

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#37]
https://developer.okta.com/docs/api/resources/schemas#update-user-profile-schema-property

okta only supports updating permissions and the nullability of the firstName and lastName fields for the base user subschema

**Comment by maneeshsahu** [comment]
+1
@ocxo @bellaweo Can you support updating base attributes? Currently, I can only create a okta_user_schema attribute, not update an existing one. 

I need the following to implement a 'Login with Apple' OIDC SSO:
1. Username: Update Format restrictions to 'None'
2. Last Name: Not required
3. First Name: Not required
