### ISSUE TITLE
Error while creating custom user schema

### ISSUE THREAD

**Issue by asiyani** [articulate/terraform-provider-okta#375]
## Expected Behavior
`okta_app_user_schema`  can be use to create/add custom user schema for any provisioned enabled app 
```
data "okta_app" "gsuite" {
  label = "Gsuite"
}

resource okta_app_user_schema "externalIdsOrganizationValue" {
  app_id        = data.okta_app.gsuite.id
  index         = "externalIdsOrganizationValue"
  title         = "ExternalIds Organization Value"
  type          = "string"
  external_name = "externalIdsOrganizationValue"
  master        = "PROFILE_MASTER"
}
```

## Actual Behavior
when using `okta_app_user_schema` as shown above to create `externalIdsOrganizationValue` in `Gsuite`  I am getting following error..
```
Error: json: cannot unmarshal object into Go struct field UserSchemaItem.definitions.base.properties.items.enum of type string

  on user_gsuite_schema.tf line 3, in resource "okta_app_user_schema" "externalIdsOrganizationValue":
   3: resource okta_app_user_schema "externalIdsOrganizationValue" {
```

## Steps to Reproduce the Problem

Environment, commands

1. terraform init
2. terraform plan -out=saved-plan 
3. terraform apply  saved-plan

## Additional info
I have used same resource to create custom schema for `BambooHR` App without any Error. I am only getting issue with `Gsuite` application. I am getting same error message while creating any other custom attributes for Gsuite app in okta. Also I can confirm that I have created those custom attributes in `Gsuite`  Not sure if this is only `GSuite` specific or any other app is also affected by this.

**Comment by quantumew** [comment]
Sorry for the delay. I am assuming Okta's API is breaking its contract here. Or if not breaking it, it is returning something we haven't accounted for, thus the marshalling error. Let me see why and get that accounted for in the response payload for this endpoint.
