### ISSUE TITLE
actions not suported on okta_group_rule?

### ISSUE THREAD

**Issue by zpol** [articulate/terraform-provider-okta#376]
I was trying to create a set of rules in Okta, but I got stucked when I realized that there's no support for actions method for okta_group_rule resource.

Doc link: https://www.terraform.io/docs/providers/okta/r/group_rule.html

There's a roadmap to include actions on ```okta_group_rule```  resource?  

I don't know if there's a work arround for this. I was thinking about using a local resource and execute a bash doing curl requests to Okta API and setting the actions for those rules but it's getting out of hand handling all the different variables... 

Some tip? 

Thanks in advance

**Comment by tgoodsell-tempus** [comment]
Hey Zpol,

Do you mind getting more into the specifics of what you mean by the group rule actions, any specific examples? 

As far as I can tell the current resource supports everything the API does, see these docs:
https://developer.okta.com/docs/reference/api/groups/#group-rule-operations

I'm wondering if you're referring to any sort of early access or beta feature they've not exposed API control for.
