### ISSUE TITLE
Create version scheme for TF provider & oktasdk-go repo

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#39]
TF versioning must follow semantic rules: https://www.hashicorp.com/blog/hashicorp-terraform-provider-versioning

need to add the version scheme to the GnuMakefile & travis yaml file

will need to add a build stage to the travis yaml file to build the go binary & possibly copy it to the s3 bucket

**Comment by bellaweo** [comment]
https://github.com/articulate/terraform-provider-okta/pull/40

**Comment by PurrBiscuit** [comment]
we have versioning enabled in the GNUMakefile for the provider versioning and also have some steps to `make ship` to the s3 bucket -https://github.com/articulate/terraform-provider-okta/blob/master/GNUmakefile#L1
