### ISSUE TITLE
Terraform provider contributions

### ISSUE THREAD

**Issue by Daniel-Houston** [articulate/terraform-provider-okta#41]
We have an okta-go-sdk and a terraform provider that is about 60-70% complete that we are thinking of open-sourcing. I would like to chat with someone about collaborating on this provider. What is the best way to do that?

**Comment by bellaweo** [comment]
Oh nice! Have you chatted with the Okta devs regarding your go sdk? They are in the process of releasing their own official go sdk but it will be very sparse to begin.

I've been working on this project for a few months now and would love to chat about collaborating.

**Comment by Daniel-Houston** [comment]
Yes, we have. We are waiting for their sdk to be released then are planning on releasing the provider with the sdk support. We could also release our sdk and provider and start there then slowly work toward using Okta's sdk once it is released. What is your plan? Are you waiting for their sdk to be released?

**Comment by robwaldron-flg** [comment]
@Daniel-Houston - I'd be happy to be an early user of what you have? We manage 10,000's of users and currently up to 50 applications in Okta.

**Comment by fromonesrc** [comment]
@Daniel-Houston we at @articulate would love to collaborate with you on this. We're currently rolling with https://github.com/articulate/oktasdk-go/.

**Comment by noinarisak** [comment]
Closed. The provider is officially apart Hashicorp Terraform. 

Related to the issue/question, Okta DevX team has plan to release, much overdue, okta-sdk-golang in early April, 2020. 🎉  https://github.com/okta/okta-sdk-golang
