### ISSUE TITLE
Generalize build pipeline for terraform providers & Document with Playbook/README update

### ISSUE THREAD

**Issue by PurrBiscuit** [articulate/terraform-provider-okta#47]

**Comment by noinarisak** [comment]
Hi @PurrBiscuit. Thanks for your interest in the project.

Closed in issue. Becoming an official Hashicorp Terraform provider required this project to adhere to Hashicorp process & procedure (ie. CI/CD process). In short, it has been implemented by default.

New location https://github.com/terraform-providers/terraform-provider-okta
