### ISSUE TITLE
Add Tenant Scope & Claim

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#5]
Add Scope

    Goto API > Authentication Servers
    Click the "default" server
    Click on the "Scopes" tab
    Click on the "Add Scope Button"
    Add a new "tenant" scope. Do not set in as the default scope.

Add Claim

    Goto API > Authentication Servers
    Click the "default" server
    Click on the "Claims" tab.
    Click "Add Claim"
    Fill out the form & click "Create"
        Name: "tenantId"
        Include in token type: "ID Token" "Always"
        Value Type: "Expression"
        Mapping: "user.tenantId"
        Disable Claim: unchecked
        Include in: the following scopes: "tenant"

**Comment by quantumew** [comment]
Done in #112
