### ISSUE TITLE
Use Google Cloud terraform provider to provision as much of the google things needed for the Oauth things in Okta

### ISSUE THREAD

**Issue by PurrBiscuit** [articulate/terraform-provider-okta#50]
It looks like the [Google Cloud](https://www.terraform.io/docs/providers/google/index.html) Terraform Provider could be used to manage some of the things that we are currently creating manually like:

  - Project
  - Oauth Credentials
  - Users with access to those things

Just need to figure out how to get that configured and what resources are needed to get the client_id/client_secret, etc.

**Comment by PurrBiscuit** [comment]
this doesn't seem possible yet from what I can tell - there isn't a terraform resource for this yet and it doesn't appear to be something that is even configurable via the API directly on Google as well - https://github.com/terraform-providers/terraform-provider-google/issues/1287

**Comment by noinarisak** [comment]
Close per @quantumew request.
