### ISSUE TITLE
Implement Group resource logic

### ISSUE THREAD

**Issue by chazu** [articulate/terraform-provider-okta#54]
Currently the group resource is just a skeleton - implement logic for actually managing Okta groups.

**Comment by quantumew** [comment]
I think this is done but don't have full context on what this was supposed to be. The only thing group management related feature that is still on the docket is group rules here -> https://github.com/articulate/terraform-provider-okta/issues/87. Wondering if we can close this in favor of that ticket? If not, maybe we can add a bit more detail to what features are missing.

**Comment by quantumew** [comment]
Groups/Group Rules/ and group related claims. Let me know if there is anything else needed.
