### ISSUE TITLE
Using the beta okta-go-sdk

### ISSUE THREAD

**Issue by robwaldron-flg** [articulate/terraform-provider-okta#62]
Hi there,

The Okta GO SDK is in beta. Should the effort be best spent on moving to that, and then no longer having to worry about attempting to implement yourself. This will also likely help with the adoption / development as the feature sets will be added quicker to the official go sdk implementation.

https://github.com/okta/okta-sdk-golang

**Comment by ocxo** [comment]
Hi @robwaldron-flg thanks for the issue. Getting on the official SDK is definitely on our radar. When we started building this provider it didn't have all the API support we needed but that has likely changed. Will take a closer look!

**Comment by quantumew** [comment]
Going to close this. Development on https://github.com/okta/okta-sdk-golang has halted. We are using a fork https://github.com/articulate/okta-sdk-golang, which has a few extra features and bug fixes. For instance, it supports retries/backoffs and some extra resources. Fortunately, when they start development again we will be using the same patterns so it should be an easy swap out. Their `develop` branch is what we are working off of.
