### ISSUE TITLE
multifactor policy for all okta administrators

### ISSUE THREAD

**Issue by PurrBiscuit** [articulate/terraform-provider-okta#84]
Need to add the ability to create multifactor authentication policies for okta users.  We'll want to be able to assign this policy to certain groups as well.  I'm not sure the best way to handle that right now; if it should be handled by the `okta_group`, the`okta_policy` or another resource of some kind.  There will be cases where we'll want to assign it to the "Everyone" group; like the internal Articulate account that folks will be using as an SSO to our other apps that they'll be admin'ing.  Then for the rise.com account we'll want to limit the users it's assigned to to just a group that may be called "Admins" or something along those lines.  We'll want customers of rise.com to determine on their own if they want their users to have MFA via the rise.com app in those cases.

**Comment by quantumew** [comment]
Going to close this, this was done back with #84 and #86. Policies can be managed by including/excluding groups, rules can by managed by doing the same at the user level.
