### ISSUE TITLE
cannot use type *bool in field value

### ISSUE THREAD

**Issue by webhull** [articulate/terraform-provider-okta#89]
Hello,

I am getting the following error when trying to "make build"

cannot use &revealPass (type *bool) as type bool in field value
cannot use &autoSubmit (type *bool) as type bool in field value
cannot use &hideMobile (type *bool) as type bool in field value
cannot use &hideWeb (type *bool) as type bool in field value
../../articulate/terraform-provider-okta/okta/app.go:162:4: cannot use &hideWeb (type *bool) as type bool in field value
../../articulate/terraform-provider-okta/okta/app.go:167:58: undefined: "github.com/okta/okta-sdk-golang/okta".App
../../articulate/terraform-provider-okta/okta/app.go:170:55: too many arguments in call to client.Application.GetApplication
../../articulate/terraform-provider-okta/okta/app.go:199:70: not enough arguments in call to client.Application.CreateApplicationGroupAssignment
	have (string, string, "github.com/okta/okta-sdk-golang/okta".ApplicationGroupAssignment)
	want (string, string, "github.com/okta/okta-sdk-golang/okta".ApplicationGroupAssignment, *query.Params)
../../articulate/terraform-provider-okta/okta/app.go:218:66: not enough arguments in call to client.Application.DeleteApplicationGroupAssignment
	have (string, string)
	want (string, string, *query.Params)
../../articulate/terraform-provider-okta/okta/app.go:268:61: not enough arguments in call to client.Application.AssignUserToApplication
	have (string, "github.com/okta/okta-sdk-golang/okta".AppUser)
	want (string, "github.com/okta/okta-sdk-golang/okta".AppUser, *query.Params)
../../articulate/terraform-provider-okta/okta/app.go:297:56: not enough arguments in call to client.Application.DeleteApplicationUser
	have (string, string)
	want (string, string, *query.Params)
../../articulate/terraform-provider-okta/okta/app.go:297:56: too many errors

go version is go1.11.2 linux/amd64

**Comment by quantumew** [comment]
Hello, due to the incompleteness of the official Okta SDK for Golang we have been using their develop branch. I am going to assume you pulled this down prior to that constraint being added and thus you are seeing a dependency mismatch. Running `dep ensure` should get you in working order. I will leave this open until you can confirm.

**Comment by webhull** [comment]
Hello,

So, you mean you are using the develop branch of the following repos, which are stored in the app.go folder

	"github.com/okta/okta-sdk-golang/okta"
	"github.com/okta/okta-sdk-golang/okta/query"

so if I understand correctly, I should replace them with the files from their develop branch ?

**Comment by quantumew** [comment]
Nope, the constraint to make this change is already in the `Gopkg.toml`, which `dep`, the thing we use to manage dependencies, will read. You will just simply have to run `dep ensure` and it should pull down the correct dependencies.

**Comment by webhull** [comment]
Hello,

Thank you very much for your kind help, everything works like a charm. I will submit another issue if a problem arise.
