### ISSUE TITLE
Document Terraform Resources

### ISSUE THREAD

**Issue by bellaweo** [articulate/terraform-provider-okta#9]
ideally, can we automate this?

Continue to add examples with links in the README as tests are written but long term make a site similar to other providers. Terraform currently hand spins all of their docs :-( and while writing a generator is the right approach it may not be time efficient.

**Comment by quantumew** [comment]
Added examples documentation that also serves as test fixtures https://github.com/articulate/terraform-provider-okta/tree/master/examples, two birds with one stone sort of thing to save time. Long term we should add an official wiki. Keeping this open but figured the context would help.

**Comment by noinarisak** [comment]
Closed. Since the provider is now officially within Hashicorp Terraform ecosystem with an automated generated documentation ci/cd system. 

ie.
https://www.terraform.io/docs/providers/okta/
