### ISSUE TITLE
Problem with the password policy types

### ISSUE THREAD

**Issue by webhull** [articulate/terraform-provider-okta#91]
Hello,

I am trying to create new password policy type, but I got the following error : 

* okta_password_policy.default: [ERROR] Error Creating Policy: HTTP Method: POST - URL: https://myaccount.okta.com/api/v1/policies: - HTTP Status Code: 400, OKTA Error Code: E0000002, OKTA Error Summary: The request was not valid: **Invalid policy type specified**., OKTA Error Causes: []

The problem is there is no place to fill the policy type. I went through Okta's website also and tried to add type field in the tf code with content PASSWORD, but it said "invalid or unknown key: type"

Here is the terraform code I use : 

provider "okta" {
  org_name  = "${var.org_name}"
  api_token = "${var.api_token}"
  base_url  = "${var.base_url}"
}

resource "okta_password_policy" "default" {
  name = "${var.name}"
  description = "${var.description}"
  groups_included = "${var.groupslist}"
  password_min_length = "${var.minlength}"
  password_min_lowercase = "${var.minlowcase}"
  password_min_uppercase = "${var.minupcase}"
  password_min_number = "${var.minnum}"
  password_min_symbol = "${var.minsym}"
  password_max_lockout_attempts = "${var.maxlockout}"
  password_auto_unlock_minutes = "${var.autounlock}"
}

I also went through your password policy and password policy rule code, but there is nothing related to the password policy type in the resources.

**Comment by quantumew** [comment]
Gotcha, yea I can confirm we are able to create password policies without issue. I can also confirm this feature is not Beta or EA. The final thing that occurs to me is the possibility that the error code is misleading us and this is simply a config issue. To debug this you could start by commenting out everything except the name and description and rule out the other config. You could also confirm the type is indeed being sent downstream to Okta. I have confirmed it is for me locally (also working on travis, recently opened a PR that ran these ACC tests).

**Comment by quantumew** [comment]
I was hoping those steps would narrow down the issue. Give me a minute and I can setup a throw away example that works for me. You will want to build the binary. `make build-linux` or `make build-mac`, that will copy it to your terraform providers directory. Eventually this will be served like other providers from a registry but it hasn't been accepted to the open source one as of yet.

**Comment by webhull** [comment]
Hello,

The problem has been resolved. FYI, when you create terraform code, the resource should be put as follows : 

resource "okta_password_policy" "legacy" {
code
code
code
}

Means - the policy should be created as legacy.

The issue can be closed.

Thank you for your kind help!

**Comment by quantumew** [comment]
Thanks for reporting back!
