### ISSUE TITLE
Integrating AWS or Google app

### ISSUE THREAD

**Issue by webhull** [articulate/terraform-provider-okta#92]
Hello,

Could you please provide more information about which resource needs to be used to integrate aws or google ? I went through the saml_app_test, but there seems to be a little bit info about this. Thanks in advance

**Comment by quantumew** [comment]
You bet. I will add a better example today. One thing to note with AWS is they don't have a way to configure API integration via their API so there are some pieces that are still manual. I am waiting to hear when they are going to add that.

**Comment by webhull** [comment]
Thanks. I will be glad to see the better example described, because at the moment it is not understandable.

**Comment by ahsanali** [comment]
Can we have this please ? :)
